import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { getServerUser } from '@/lib/get-server-user'
import { getEffectivePermissions } from '@/lib/permission-utils'
import { updateExpenseAccountBalanceTx, calculateExpenseAccountBalance } from '@/lib/expense-account-utils'

/**
 * POST /api/business-loans/[loanId]/pre-lock-repayments
 * Record a pre-lock repayment (partial payback before the account is locked).
 * Access: assigned user only while status is RECORDING.
 */
export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ loanId: string }> }
) {
  try {
    const user = await getServerUser()
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const { loanId } = await params

    const loan = await prisma.businessLoan.findUnique({
      where: { id: loanId },
      select: {
        id: true,
        status: true,
        managedByUserId: true,
        expenseAccountId: true,
      },
    })
    if (!loan) {
      return NextResponse.json({ error: 'Loan not found' }, { status: 404 })
    }

    const permissions = getEffectivePermissions(user)
    const isAdmin = permissions.canManageBusinessLoans
    const isManager = loan.managedByUserId === user.id ||
      !!(await prisma.businessLoanManager.findUnique({ where: { loanId_userId: { loanId: loan.id, userId: user.id } } }))

    if (!isAdmin && !isManager) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
    }

    if (loan.status !== 'RECORDING') {
      return NextResponse.json(
        { error: 'Pre-lock repayments can only be added while the loan is in RECORDING status' },
        { status: 400 }
      )
    }

    const body = await request.json()
    const { description, amount, repaymentDate, notes } = body

    if (!description || !amount || !repaymentDate) {
      return NextResponse.json(
        { error: 'description, amount, and repaymentDate are required' },
        { status: 400 }
      )
    }

    const parsedAmount = Number(amount)
    if (isNaN(parsedAmount) || parsedAmount <= 0) {
      return NextResponse.json({ error: 'amount must be a positive number' }, { status: 400 })
    }

    // Validate: repayment cannot push balance above $0 (account must stay at 0 or negative)
    const currentBalance = await calculateExpenseAccountBalance(loan.expenseAccountId)
    if (currentBalance + parsedAmount > 0) {
      return NextResponse.json(
        {
          error: 'Repayment would exceed the current outstanding balance',
          currentBalance,
          maxRepayment: Math.abs(currentBalance),
        },
        { status: 400 }
      )
    }

    const { repayment, newBalance } = await prisma.$transaction(async (tx) => {
      const repayment = await tx.businessLoanPreLockRepayment.create({
        data: {
          loanId,
          description,
          amount: parsedAmount,
          repaymentDate: new Date(repaymentDate),
          notes: notes ?? null,
          createdByUserId: user.id,
        },
      })

      // Mirror into ExpenseAccountDeposits so balance calculation stays consistent
      await tx.expenseAccountDeposits.create({
        data: {
          expenseAccountId: loan.expenseAccountId,
          sourceType: 'LOAN_PRE_LOCK_REPAYMENT',
          amount: parsedAmount,
          depositDate: new Date(repaymentDate),
          manualNote: repayment.id,
          autoGeneratedNote: 'Pre-lock loan repayment',
          createdByUserId: user.id,
        },
      })

      const newBalance = await updateExpenseAccountBalanceTx(tx, loan.expenseAccountId)
      return { repayment, newBalance }
    })

    return NextResponse.json({ repayment, newBalance }, { status: 201 })
  } catch (error) {
    console.error('POST /api/business-loans/[loanId]/pre-lock-repayments error:', error)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
