import { NextRequest, NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import { prisma } from '@/lib/prisma'
import {
  getGlobalPayrollAccount,
  validateDepositAmount,
  checkBusinessAccountBalance,
  debitBusinessAccount,
  generateDepositNote,
  updatePayrollAccountBalance,
} from '@/lib/payroll-account-utils'

/**
 * GET /api/payroll/account/deposits
 * Get list of payroll account deposits with pagination
 *
 * Query params:
 * - businessId: Filter by source business (optional)
 * - startDate: Filter deposits from this date (optional)
 * - endDate: Filter deposits up to this date (optional)
 * - limit: Number of deposits to return (default: 20)
 * - offset: Number of deposits to skip (default: 0)
 * - transactionType: Filter by type (PAYROLL_EXPENSE | MANUAL_TRANSFER) (optional)
 */
export async function GET(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions)
    if (!session?.user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // TODO: Add permission check for canViewPayrollHistory

    // Get global payroll account
    const payrollAccount = await getGlobalPayrollAccount()
    if (!payrollAccount) {
      return NextResponse.json(
        { error: 'Payroll account not found' },
        { status: 404 }
      )
    }

    // Get query params
    const { searchParams } = new URL(request.url)
    const businessId = searchParams.get('businessId')
    const startDate = searchParams.get('startDate')
    const endDate = searchParams.get('endDate')
    const transactionType = searchParams.get('transactionType')
    const limit = parseInt(searchParams.get('limit') || '20')
    const offset = parseInt(searchParams.get('offset') || '0')

    // Build where clause
    const where: any = {
      payrollAccountId: payrollAccount.id,
    }

    if (businessId) {
      where.sourceBusinessId = businessId
    }

    if (startDate || endDate) {
      where.depositDate = {}
      if (startDate) {
        where.depositDate.gte = new Date(startDate)
      }
      if (endDate) {
        where.depositDate.lte = new Date(endDate)
      }
    }

    if (transactionType) {
      where.transactionType = transactionType
    }

    // Get deposits with pagination
    const [deposits, totalCount] = await Promise.all([
      prisma.payrollAccountDeposits.findMany({
        where,
        include: {
          businesses: {
            select: { id: true, name: true, type: true },
          },
          users: {
            select: { id: true, name: true, email: true },
          },
          business_expenses: {
            select: {
              id: true,
              categoryId: true,
              amount: true,
              expenseDate: true,
              description: true,
            },
          },
        },
        orderBy: { depositDate: 'desc' },
        take: limit,
        skip: offset,
      }),
      prisma.payrollAccountDeposits.count({ where }),
    ])

    return NextResponse.json({
      success: true,
      data: {
        deposits: deposits.map((d) => ({
          id: d.id,
          amount: Number(d.amount),
          depositDate: d.depositDate,
          autoGeneratedNote: d.autoGeneratedNote,
          transactionType: d.transactionType,
          business: d.businesses,
          createdBy: d.users,
          linkedExpense: d.business_expenses,
          createdAt: d.createdAt,
        })),
        pagination: {
          total: totalCount,
          limit,
          offset,
          hasMore: offset + limit < totalCount,
        },
      },
    })
  } catch (error) {
    console.error('Error fetching payroll account deposits:', error)
    return NextResponse.json(
      { error: 'Failed to fetch payroll account deposits' },
      { status: 500 }
    )
  }
}

/**
 * POST /api/payroll/account/deposits
 * Create a new deposit from business account to payroll account
 *
 * Body:
 * - sourceBusinessId: string (required)
 * - amount: number (required)
 * - transactionType: "PAYROLL_EXPENSE" | "MANUAL_TRANSFER" (optional, default: MANUAL_TRANSFER)
 * - note: string (optional, auto-generated if not provided)
 * - expenseId: string (optional, link to business expense if auto-generated)
 */
export async function POST(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions)
    if (!session?.user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // TODO: Add permission check for canMakePayrollDeposits
    // TODO: Check user has payroll deposit permission for the source business

    // Get global payroll account
    const payrollAccount = await getGlobalPayrollAccount()
    if (!payrollAccount) {
      return NextResponse.json(
        { error: 'Payroll account not found' },
        { status: 404 }
      )
    }

    // Parse request body
    const body = await request.json()
    const {
      sourceBusinessId,
      amount,
      transactionType = 'MANUAL_TRANSFER',
      note,
      expenseId,
    } = body

    // Validate required fields
    if (!sourceBusinessId) {
      return NextResponse.json(
        { error: 'Source business ID is required' },
        { status: 400 }
      )
    }

    if (amount === undefined || amount === null) {
      return NextResponse.json(
        { error: 'Amount is required' },
        { status: 400 }
      )
    }

    // Validate amount
    const amountValidation = validateDepositAmount(Number(amount))
    if (!amountValidation.valid) {
      return NextResponse.json(
        { error: amountValidation.error },
        { status: 400 }
      )
    }

    // Check if source business exists
    const sourceBusiness = await prisma.businesses.findUnique({
      where: { id: sourceBusinessId },
      select: { id: true, name: true, type: true },
    })

    if (!sourceBusiness) {
      return NextResponse.json(
        { error: 'Source business not found' },
        { status: 404 }
      )
    }

    // Check business account balance
    const hasSufficientBalance = await checkBusinessAccountBalance(
      sourceBusinessId,
      Number(amount)
    )

    if (!hasSufficientBalance) {
      return NextResponse.json(
        { error: 'Insufficient balance in business account' },
        { status: 400 }
      )
    }

    // Generate deposit note if not provided
    const depositNote =
      note || generateDepositNote(sourceBusiness.name, transactionType)

    // Use transaction to ensure atomicity
    const result = await prisma.$transaction(async (tx) => {
      // 1. Debit business account
      const debitResult = await debitBusinessAccount(
        sourceBusinessId,
        Number(amount),
        depositNote,
        session.user.id
      )

      // 2. Create deposit record
      const deposit = await tx.payrollAccountDeposits.create({
        data: {
          payrollAccountId: payrollAccount.id,
          sourceBusinessId,
          amount: Number(amount),
          autoGeneratedNote: depositNote,
          transactionType,
          createdBy: session.user.id,
          expenseId: expenseId || null,
        },
        include: {
          businesses: {
            select: { id: true, name: true, type: true },
          },
          users: {
            select: { id: true, name: true, email: true },
          },
        },
      })

      // 3. Update payroll account balance (using transaction client)
      // Calculate new balance from all deposits and payments within this transaction
      const depositsSum = await tx.payrollAccountDeposits.aggregate({
        where: { payrollAccountId: payrollAccount.id },
        _sum: { amount: true },
      })

      const paymentsSum = await tx.payrollPayments.aggregate({
        where: { payrollAccountId: payrollAccount.id },
        _sum: { amount: true },
      })

      const totalDeposits = Number(depositsSum._sum.amount || 0)
      const totalPayments = Number(paymentsSum._sum.amount || 0)
      const newBalance = totalDeposits - totalPayments

      // Update the payroll account balance
      await tx.payrollAccounts.update({
        where: { id: payrollAccount.id },
        data: { balance: newBalance, updatedAt: new Date() },
      })

      return { deposit, newBalance, debitResult }
    })

    return NextResponse.json(
      {
        success: true,
        message: 'Deposit created successfully',
        data: {
          deposit: {
            id: result.deposit.id,
            amount: Number(result.deposit.amount),
            depositDate: result.deposit.depositDate,
            autoGeneratedNote: result.deposit.autoGeneratedNote,
            transactionType: result.deposit.transactionType,
            sourceBusiness: result.deposit.businesses,
            createdBy: result.deposit.users,
            createdAt: result.deposit.createdAt,
          },
          payrollAccountBalance: result.newBalance,
          businessAccountBalance: result.debitResult.newBalance,
        },
      },
      { status: 201 }
    )
  } catch (error) {
    console.error('Error creating payroll account deposit:', error)
    return NextResponse.json(
      {
        error:
          error instanceof Error
            ? error.message
            : 'Failed to create payroll account deposit',
      },
      { status: 500 }
    )
  }
}
