'use client'

import { BusinessProtectedRoute } from '@/components/auth/business-protected-route'
import { ContentLayout } from '@/components/layout/content-layout'
import { useState, useEffect, useMemo, useCallback } from 'react'
import { useSearchParams, useRouter } from 'next/navigation'
import { useSession } from 'next-auth/react'
import { formatDateByFormat } from '@/lib/country-codes'
import { useDateFormat } from '@/contexts/settings-context'
import { useAlert } from '@/components/ui/confirm-modal'
import { BusinessBalanceDisplay } from '@/components/business/business-balance-display'
import { LoanBreakdownCard } from '@/components/business/loan-breakdown-card'
import { BalanceValidationWarning } from '@/components/business/balance-validation-warning'
import { useBusinessBalance } from '@/hooks/useBusinessBalance'
import { PhoneNumberInput } from '@/components/ui/phone-number-input'
import { NationalIdInput } from '@/components/ui/national-id-input'
import Link from 'next/link'

interface Business {
  id: string
  name: string
  type: string
  description?: string
  isUmbrellaBusiness?: boolean
  isUserBusiness?: boolean
}

interface Loan {
  id: string
  loanNumber: string
  principalAmount: number
  remainingBalance: number
  totalAmount: number
  interestRate: number
  lenderType: string
  borrowerType: string
  status: string
  loanDate: string
  dueDate?: string
  terms?: string
  notes?: string
  borrowerBusinessId?: string
  lenderBusinessId?: string
  borrowerBusiness?: { name: string }
  lenderBusiness?: { name: string }
  persons_lender?: { fullName: string }
  persons_borrower?: { fullName: string }
  loanTransactions: Array<{
    id: string
    transactionType: string
    amount: number
    description: string
    transactionDate: string
    isAutoGenerated: boolean
  }>
}

interface Lender {
  id: string
  name: string
  displayName: string
  lenderType: 'individual' | 'bank'
}

export default function BusinessLoansPage() {
  const { data: session } = useSession()
  const searchParams = useSearchParams()
  const router = useRouter()
  const globalDateFormat = useDateFormat()
  const customAlert = useAlert()
  const [loans, setLoans] = useState<Loan[]>([])
  const [businesses, setBusinesses] = useState<Business[]>([])
  const [lenders, setLenders] = useState<Lender[]>([])
  const [loading, setLoading] = useState(true)
  const [showCreateLoanModal, setShowCreateLoanModal] = useState(false)
  const [showLoanDetailsModal, setShowLoanDetailsModal] = useState(false)
  const [showPaymentModal, setShowPaymentModal] = useState(false)
  const [selectedLoan, setSelectedLoan] = useState<Loan | null>(null)
  const [loanFilter, setLoanFilter] = useState<'all' | 'business' | 'external_lender' | 'business_to_person'>('all')
  const [selectedBreakdownBusinessId, setSelectedBreakdownBusinessId] = useState<string>('')

  // Quick lender creation modal
  const [showQuickLenderModal, setShowQuickLenderModal] = useState(false)
  const [quickLender, setQuickLender] = useState({
    fullName: '',
    email: '',
    phone: '',
    nationalId: '',
    nationalIdTemplateId: '',
    address: '',
    lenderType: 'individual' as 'individual' | 'bank',
    notes: '',
    bankRegistrationNo: '',
    swiftCode: '',
    branchCode: '',
    city: '',
    country: ''
  })

  // Handle viewLoan query parameter to auto-open loan details
  const viewLoanId = searchParams.get('viewLoan')

  useEffect(() => {
    if (viewLoanId && loans.length > 0 && !showLoanDetailsModal) {
      const loanToView = loans.find(l => l.id === viewLoanId)
      if (loanToView) {
        setSelectedLoan(loanToView)
        setShowLoanDetailsModal(true)
        // Clear the query param
        router.replace('/business/manage/loans', { scroll: false })
      }
    }
  }, [viewLoanId, loans, showLoanDetailsModal, router])

  const [newLoan, setNewLoan] = useState({
    lenderType: 'business' as 'business' | 'person',
    lenderBusinessId: '',
    lenderPersonId: '',
    borrowerType: 'business' as 'business' | 'person',
    borrowerBusinessId: '',
    borrowerPersonId: '',
    principalAmount: '',
    interestRate: '0',
    terms: '',
    notes: '',
    loanDate: new Date().toISOString().split('T')[0],
    dueDate: '',
    transferType: 'loan' // 'loan' or 'profit_transfer'
  })

  const [newPayment, setNewPayment] = useState({
    transactionType: 'payment',
    amount: '',
    description: '',
    transactionDate: new Date().toISOString().split('T')[0],
    notes: ''
  })

  // Filter loans based on selected filter
  const filteredLoans = useMemo(() => {
    if (loanFilter === 'all') return loans
    if (loanFilter === 'business') {
      return loans.filter(loan => loan.lenderType === 'business' && loan.borrowerType === 'business')
    }
    if (loanFilter === 'external_lender') {
      return loans.filter(loan => loan.lenderType === 'person')
    }
    if (loanFilter === 'business_to_person') {
      return loans.filter(loan => loan.lenderType === 'business' && loan.borrowerType === 'person')
    }
    return loans
  }, [loans, loanFilter])

  // Balance tracking for loan creation (only for business lenders)
  const lenderBalance = useBusinessBalance(
    newLoan.lenderType === 'business' ? (newLoan.lenderBusinessId || null) : null
  )

  // For payments: borrower business pays, for advances: lender business pays
  const getPaymentBusinessId = () => {
    if (!selectedLoan) return null

    if (newPayment.transactionType === 'payment') {
      // Payment: borrower business is paying - use borrowerBusinessId from loan
      return selectedLoan.borrowerBusinessId || null
    } else {
      // Advance: lender business is paying - use lenderBusinessId from loan
      return selectedLoan.lenderBusinessId || null
    }
  }

  const paymentBusinessBalance = useBusinessBalance(getPaymentBusinessId())

  // Validation for loan creation (only validate balance for business lenders)
  const loanValidation = useMemo(() => {
    if (newLoan.lenderType === 'person') return null // External lenders don't need validation
    if (!newLoan.lenderBusinessId || !newLoan.principalAmount) return null
    const amount = parseFloat(newLoan.principalAmount)
    if (isNaN(amount) || amount <= 0) return null
    return lenderBalance.validateAmount(amount)
  }, [newLoan.lenderType, newLoan.lenderBusinessId, newLoan.principalAmount, lenderBalance])

  // Validation for payments
  const paymentValidation = useMemo(() => {
    if (!selectedLoan || !newPayment.amount) return null
    const amount = parseFloat(newPayment.amount)
    if (isNaN(amount) || amount <= 0) return null
    return paymentBusinessBalance.validateAmount(amount)
  }, [selectedLoan, newPayment.amount, paymentBusinessBalance])

  // Helper function to format dates according to global settings
  const formatDate = (dateString: string) => {
    if (!dateString) return ''
    return formatDateByFormat(dateString, globalDateFormat)
  }

  useEffect(() => {
    fetchLoans()
    fetchBusinesses()
    fetchLenders()
  }, [])

  const fetchLoans = async () => {
    try {
      const response = await fetch('/api/business/loans', { credentials: 'include' })
      if (response.ok) {
        const data = await response.json()
        setLoans(Array.isArray(data) ? data : [])
      }
    } catch (error) {
      console.error('Failed to fetch loans:', error)
      setLoans([])
    } finally {
      setLoading(false)
    }
  }

  const fetchBusinesses = async () => {
    try {
      const response = await fetch('/api/business/available-borrowers', { credentials: 'include' })
      if (response.ok) {
        const data = await response.json()
        setBusinesses(Array.isArray(data) ? data : [])
      }
    } catch (error) {
      console.error('Failed to fetch businesses:', error)
      setBusinesses([])
    }
  }

  const fetchLenders = async () => {
    try {
      const response = await fetch('/api/business/available-lenders', { credentials: 'include' })
      if (response.ok) {
        const data = await response.json()
        setLenders(Array.isArray(data) ? data : [])
      }
    } catch (error) {
      console.error('Failed to fetch lenders:', error)
      setLenders([])
    }
  }

  const handleQuickLenderCreate = async (e: React.FormEvent) => {
    e.preventDefault()

    // Validation based on lender type
    if (quickLender.lenderType === 'bank') {
      if (!quickLender.fullName || !quickLender.phone || !quickLender.bankRegistrationNo || !quickLender.address || !quickLender.city || !quickLender.country) {
        await customAlert({ title: 'Validation', description: 'Bank name, phone, registration number, address, city, and country are required for banks' })
        return
      }
    } else {
      if (!quickLender.fullName || !quickLender.phone || !quickLender.nationalId) {
        await customAlert({ title: 'Validation', description: 'Full name, phone, and national ID are required for individuals' })
        return
      }
    }

    try {
      const response = await fetch('/api/business/lenders', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify(quickLender)
      })

      if (response.ok) {
        const newLenderData = await response.json()
        await fetchLenders()
        // Auto-select the newly created lender
        if (newLenderData.id) {
          setNewLoan(prev => ({ ...prev, lenderPersonId: newLenderData.id }))
        }
        setShowQuickLenderModal(false)
        setQuickLender({
          fullName: '',
          email: '',
          phone: '',
          nationalId: '',
          nationalIdTemplateId: '',
          address: '',
          lenderType: 'individual',
          notes: '',
          bankRegistrationNo: '',
          swiftCode: '',
          branchCode: '',
          city: '',
          country: ''
        })
        await customAlert({ title: 'Success', description: 'Lender created! You can now select them from the dropdown.' })
      } else {
        const error = await response.json()
        await customAlert({ title: 'Error', description: error.error || 'Failed to create lender' })
      }
    } catch (error) {
      console.error('Error creating lender:', error)
      await customAlert({ title: 'Error', description: 'Error creating lender' })
    }
  }

  const handleCreateLoan = async (e: React.FormEvent) => {
    e.preventDefault()

    // Validate lender
    if (newLoan.lenderType === 'business' && !newLoan.lenderBusinessId) {
      await customAlert({ title: 'Validation', description: 'Please select a lender business' })
      return
    }
    if (newLoan.lenderType === 'person' && !newLoan.lenderPersonId) {
      await customAlert({ title: 'Validation', description: 'Please select a lender' })
      return
    }

    // Validate borrower
    if (newLoan.borrowerType === 'business' && !newLoan.borrowerBusinessId) {
      await customAlert({ title: 'Validation', description: 'Please select a borrower business' })
      return
    }
    if (newLoan.borrowerType === 'person' && !newLoan.borrowerPersonId) {
      await customAlert({ title: 'Validation', description: 'Please select a borrower' })
      return
    }

    if (!newLoan.principalAmount) {
      await customAlert({ title: 'Validation', description: 'Please enter a principal amount' })
      return
    }

    // Prevent self-loans (business lending to itself)
    if (newLoan.lenderType === 'business' && newLoan.borrowerType === 'business' &&
        newLoan.lenderBusinessId === newLoan.borrowerBusinessId) {
      await customAlert({ title: 'Invalid selection', description: 'A business cannot loan money to itself. Please select different lender and borrower businesses.' })
      return
    }

    try {
      const response = await fetch('/api/business/loans', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({
          lenderType: newLoan.lenderType,
          lenderBusinessId: newLoan.lenderType === 'business' ? newLoan.lenderBusinessId : null,
          lenderPersonId: newLoan.lenderType === 'person' ? newLoan.lenderPersonId : null,
          borrowerType: newLoan.borrowerType,
          borrowerBusinessId: newLoan.borrowerType === 'business' ? newLoan.borrowerBusinessId : null,
          borrowerPersonId: newLoan.borrowerType === 'person' ? newLoan.borrowerPersonId : null,
          principalAmount: parseFloat(newLoan.principalAmount),
          interestRate: parseFloat(newLoan.interestRate) || 0,
          terms: newLoan.terms,
          notes: newLoan.notes,
          loanDate: newLoan.loanDate,
          dueDate: newLoan.dueDate || null,
          transferType: newLoan.transferType
        })
      })

      if (response.ok) {
        await fetchLoans()
        setShowCreateLoanModal(false)
        setNewLoan({
          lenderType: 'business',
          lenderBusinessId: '',
          lenderPersonId: '',
          borrowerType: 'business',
          borrowerBusinessId: '',
          borrowerPersonId: '',
          principalAmount: '',
          interestRate: '0',
          terms: '',
          notes: '',
          loanDate: new Date().toISOString().split('T')[0],
          dueDate: '',
          transferType: 'loan'
        })
        await customAlert({ title: 'Success', description: 'Loan created successfully!' })
      } else {
        const error = await response.json()
        await customAlert({ title: 'Create loan failed', description: `Failed to create loan: ${error.error || 'Unknown error'}` })
      }
    } catch (error) {
      console.error('Error creating loan:', error)
      await customAlert({ title: 'Create loan failed', description: 'Error creating loan' })
    }
  }

  const handleLoanClick = (loan: Loan) => {
    setSelectedLoan(loan)
    setShowLoanDetailsModal(true)
  }

  const handlePaymentClick = (loan: Loan) => {
    setSelectedLoan(loan)
    setShowPaymentModal(true)
  }

  const handleMakePayment = async (e: React.FormEvent) => {
    e.preventDefault()
    
    if (!selectedLoan || !newPayment.amount || !newPayment.description) {
      await customAlert({ title: 'Validation', description: 'Please fill in all required fields' })
      return
    }

    try {
      const response = await fetch(`/api/business/loans/${selectedLoan.id}/transactions`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({
          transactionType: newPayment.transactionType,
          amount: parseFloat(newPayment.amount),
          description: newPayment.description,
          transactionDate: newPayment.transactionDate,
          notes: newPayment.notes
        })
      })

      if (response.ok) {
        await fetchLoans() // Refresh loan data
        setShowPaymentModal(false)
        setNewPayment({
          transactionType: 'payment',
          amount: '',
          description: '',
          transactionDate: new Date().toISOString().split('T')[0],
          notes: ''
        })
        await customAlert({ title: 'Success', description: 'Payment processed successfully!' })
      } else {
        const error = await response.json()
        await customAlert({ title: 'Payment failed', description: `Failed to process payment: ${error.error || 'Unknown error'}` })
      }
    } catch (error) {
      console.error('Error processing payment:', error)
      await customAlert({ title: 'Payment failed', description: 'Error processing payment' })
    }
  }

  return (
    <BusinessProtectedRoute requiredPermission="canAccessFinancialData">
      <ContentLayout
        title="💰 Business Loans"
        breadcrumb={[
          { label: 'Dashboard', href: '/dashboard' },
          { label: 'Business Management', href: '/business/manage' },
          { label: 'Loans', isActive: true }
        ]}
        headerActions={
          <div className="flex gap-3">
            <Link
              href="/business/manage/lenders"
              className="btn-secondary"
            >
              👥 Manage Lenders
            </Link>
            <Link
              href="/business/manage/loans/analytics"
              className="btn-secondary"
            >
              📊 View Analytics
            </Link>
            <button
              onClick={() => setShowCreateLoanModal(true)}
              className="btn-primary"
            >
              💰 Create New Loan
            </button>
          </div>
        }
      >
        <div className="space-y-6">
          {/* Loans Statistics */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            <div className="card p-6">
              <h3 className="text-lg font-semibold text-primary mb-2">Total Loans</h3>
              <p className="text-3xl font-bold text-blue-600">{loans.length}</p>
            </div>
            <div className="card p-6">
              <h3 className="text-lg font-semibold text-primary mb-2">Active Loans</h3>
              <p className="text-3xl font-bold text-green-600">
                {loans.filter(loan => loan.status === 'active').length}
              </p>
            </div>
            <div className="card p-6">
              <h3 className="text-lg font-semibold text-primary mb-2">Total Outstanding</h3>
              <p className="text-3xl font-bold text-orange-600">
                ${loans.reduce((sum, loan) => sum + (loan.status === 'active' ? loan.remainingBalance : 0), 0).toFixed(2)}
              </p>
            </div>
            <div className="card p-6">
              <h3 className="text-lg font-semibold text-primary mb-2">Paid Loans</h3>
              <p className="text-3xl font-bold text-gray-600">
                {loans.filter(loan => loan.status === 'paid').length}
              </p>
            </div>
          </div>

          {/* Lender Type Breakdown */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            <div className="card p-6 bg-blue-50 dark:bg-blue-900/20">
              <h3 className="text-sm font-semibold text-primary mb-2">🏢 Business-to-Business</h3>
              <p className="text-2xl font-bold text-blue-600">
                {loans.filter(loan => loan.lenderType === 'business' && loan.borrowerType === 'business').length}
              </p>
              <p className="text-xs text-secondary mt-1">
                ${loans.filter(loan => loan.lenderType === 'business' && loan.borrowerType === 'business' && loan.status === 'active')
                  .reduce((sum, loan) => sum + loan.remainingBalance, 0).toFixed(2)} outstanding
              </p>
            </div>
            <div className="card p-6 bg-purple-50 dark:bg-purple-900/20">
              <h3 className="text-sm font-semibold text-primary mb-2">👤 External Lender Loans</h3>
              <p className="text-2xl font-bold text-purple-600">
                {loans.filter(loan => loan.lenderType === 'person').length}
              </p>
              <p className="text-xs text-secondary mt-1">
                ${loans.filter(loan => loan.lenderType === 'person' && loan.status === 'active')
                  .reduce((sum, loan) => sum + loan.remainingBalance, 0).toFixed(2)} outstanding
              </p>
            </div>
            <div className="card p-6 bg-green-50 dark:bg-green-900/20">
              <h3 className="text-sm font-semibold text-primary mb-2">🏢 Business-to-Person Loans</h3>
              <p className="text-2xl font-bold text-green-600">
                {loans.filter(loan => loan.lenderType === 'business' && loan.borrowerType === 'person').length}
              </p>
              <p className="text-xs text-secondary mt-1">
                ${loans.filter(loan => loan.lenderType === 'business' && loan.borrowerType === 'person' && loan.status === 'active')
                  .reduce((sum, loan) => sum + loan.remainingBalance, 0).toFixed(2)} outstanding
              </p>
            </div>
          </div>

          {/* Per-Business Loan Breakdown */}
          {businesses.filter(b => b.isUserBusiness).length > 0 && (
            <div className="card p-6">
              <div className="flex items-center gap-4 mb-4">
                <h3 className="text-lg font-semibold text-primary">Business Loan Breakdown</h3>
                <select
                  value={selectedBreakdownBusinessId}
                  onChange={(e) => setSelectedBreakdownBusinessId(e.target.value)}
                  className="px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-primary focus:outline-none focus:ring-2 focus:ring-blue-500"
                >
                  <option value="">Select a business...</option>
                  {businesses.filter(b => b.isUserBusiness).map(business => (
                    <option key={business.id} value={business.id}>
                      {business.name}
                    </option>
                  ))}
                </select>
              </div>
              {selectedBreakdownBusinessId && (
                <LoanBreakdownCard
                  businessId={selectedBreakdownBusinessId}
                  className="mt-4"
                />
              )}
              {!selectedBreakdownBusinessId && (
                <p className="text-sm text-secondary">
                  Select a business to view its loan breakdown (loans received as borrower).
                </p>
              )}
            </div>
          )}

          {/* Loans Table */}
          <div className="card">
            <div className="p-6 border-b border-gray-200 dark:border-gray-700 space-y-4">
              <div className="flex justify-between items-center">
                <h2 className="text-xl font-semibold text-primary">Loan Management</h2>
                {/* Loan Type Filter */}
                <div className="flex items-center gap-2">
                  <label className="text-sm font-medium text-secondary">Filter:</label>
                  <select
                    value={loanFilter}
                    onChange={(e) => setLoanFilter(e.target.value as any)}
                    className="px-3 py-1.5 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-primary text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                  >
                    <option value="all">All Loans ({loans.length})</option>
                    <option value="business">🏢 Business-to-Business ({loans.filter(l => l.lenderType === 'business' && l.borrowerType === 'business').length})</option>
                    <option value="external_lender">👤 From External Lenders ({loans.filter(l => l.lenderType === 'person').length})</option>
                    <option value="business_to_person">🏢 Business-to-Person ({loans.filter(l => l.lenderType === 'business' && l.borrowerType === 'person').length})</option>
                  </select>
                </div>
              </div>
            </div>
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead className="bg-gray-50 dark:bg-gray-700">
                  <tr>
                    <th className="px-6 py-3 text-left text-xs font-medium text-secondary uppercase">Loan #</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-secondary uppercase">Type</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-secondary uppercase">Lender → Borrower</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-secondary uppercase">Principal</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-secondary uppercase">Balance</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-secondary uppercase">Interest</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-secondary uppercase">Status</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-secondary uppercase">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-200 dark:divide-gray-700">
                  {loading ? (
                    <tr>
                      <td colSpan={8} className="px-6 py-8 text-center text-secondary">
                        Loading loans...
                      </td>
                    </tr>
                  ) : filteredLoans.length === 0 ? (
                    <tr>
                      <td colSpan={8} className="px-6 py-8 text-center text-secondary">
                        {loans.length === 0
                          ? 'No loans found. Create your first loan to get started!'
                          : 'No loans match the selected filter.'}
                      </td>
                    </tr>
                  ) : (
                    filteredLoans.map(loan => (
                      <tr 
                        key={loan.id}
                        className="hover:bg-gray-50 dark:hover:bg-gray-700 cursor-pointer transition-colors"
                        onClick={() => handleLoanClick(loan)}
                      >
                        <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-primary">
                          {loan.loanNumber}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <span className={`px-2 py-1 text-xs font-medium rounded ${
                            loan.terms?.includes('[PROFIT_TRANSFER]')
                              ? 'bg-green-100 text-green-800'
                              : 'bg-blue-100 text-blue-800'
                          }`}>
                            {loan.terms?.includes('[PROFIT_TRANSFER]') ? '📈 Profit Transfer' : '🏢 B2B Loan'}
                          </span>
                        </td>
                        <td className="px-6 py-4 text-sm text-primary">
                          {loan.lenderType === 'person'
                            ? (loan.persons_lender?.fullName || 'External Lender')
                            : (loan.lenderBusiness?.name || 'Your Business')}
                          {' → '}
                          {loan.borrowerType === 'person'
                            ? (loan.persons_borrower?.fullName || 'Individual')
                            : (loan.borrowerBusiness?.name || 'Unknown')}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-primary">
                          ${loan.principalAmount.toFixed(2)}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-orange-600">
                          ${loan.remainingBalance.toFixed(2)}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-primary">
                          {loan.interestRate}%
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <span className={`px-2 py-1 text-xs font-medium rounded ${
                            loan.status === 'active' 
                              ? 'bg-green-100 text-green-800' 
                              : loan.status === 'paid'
                              ? 'bg-gray-100 text-gray-800'
                              : 'bg-red-100 text-red-800'
                          }`}>
                            {loan.status.charAt(0).toUpperCase() + loan.status.slice(1)}
                          </span>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm">
                          <div className="flex gap-2">
                            <button
                              onClick={(e) => {
                                e.stopPropagation()
                                handleLoanClick(loan)
                              }}
                              className="text-blue-600 hover:text-blue-800 dark:text-blue-400 dark:hover:text-blue-300 font-medium"
                            >
                              View Details
                            </button>
                            {loan.status === 'active' && loan.remainingBalance > 0 && (
                              <button
                                onClick={(e) => {
                                  e.stopPropagation()
                                  handlePaymentClick(loan)
                                }}
                                className="text-green-600 hover:text-green-800 dark:text-green-400 dark:hover:text-green-300 font-medium"
                              >
                                Make Payment
                              </button>
                            )}
                          </div>
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
          </div>
        </div>

        {/* Create Loan Modal */}
        {showCreateLoanModal && (
          <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
            <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-xl max-w-md w-full mx-4">
              <h2 className="text-xl font-semibold text-primary mb-4">
                {newLoan.transferType === 'profit_transfer' ? 'Create Profit Transfer' : 'Create New Loan'}
              </h2>
              <form onSubmit={handleCreateLoan} className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-secondary mb-2">
                    Transfer Type *
                  </label>
                  <div className="flex gap-4">
                    <label className="flex items-center">
                      <input
                        type="radio"
                        name="transferType"
                        value="loan"
                        checked={newLoan.transferType === 'loan'}
                        onChange={(e) => setNewLoan({
                          ...newLoan,
                          transferType: e.target.value,
                          interestRate: e.target.value === 'loan' ? '0' : '0',
                          terms: e.target.value === 'profit_transfer' ? 'Profit transfer - no repayment required' : ''
                        })}
                        className="mr-2"
                      />
                      💰 Business Loan
                    </label>
                    <label className="flex items-center">
                      <input
                        type="radio"
                        name="transferType"
                        value="profit_transfer"
                        checked={newLoan.transferType === 'profit_transfer'}
                        onChange={(e) => setNewLoan({
                          ...newLoan,
                          transferType: e.target.value,
                          interestRate: '0',
                          terms: e.target.value === 'profit_transfer' ? 'Profit transfer - no repayment required' : ''
                        })}
                        className="mr-2"
                      />
                      📈 Profit Transfer
                    </label>
                  </div>
                </div>

                {/* Lender Type Selection */}
                <div>
                  <label className="block text-sm font-medium text-secondary mb-2">
                    Lender Type *
                  </label>
                  <div className="flex gap-4">
                    <label className="flex items-center">
                      <input
                        type="radio"
                        name="lenderType"
                        value="business"
                        checked={newLoan.lenderType === 'business'}
                        onChange={(e) => setNewLoan({
                          ...newLoan,
                          lenderType: 'business',
                          lenderPersonId: '',
                          lenderBusinessId: ''
                        })}
                        className="mr-2"
                      />
                      🏢 Business
                    </label>
                    <label className="flex items-center">
                      <input
                        type="radio"
                        name="lenderType"
                        value="person"
                        checked={newLoan.lenderType === 'person'}
                        onChange={(e) => setNewLoan({
                          ...newLoan,
                          lenderType: 'person',
                          lenderBusinessId: '',
                          lenderPersonId: ''
                        })}
                        className="mr-2"
                      />
                      👤 Individual/Bank
                    </label>
                  </div>
                  <p className="mt-2 text-xs text-gray-600 dark:text-gray-400">
                    💡 <strong>Business:</strong> Loan from one of your businesses (requires balance validation).
                    <strong className="ml-2">Individual/Bank:</strong> Loan from external person or financial institution (no balance validation required).
                  </p>
                </div>

                {/* Lender Selection */}
                {newLoan.lenderType === 'business' ? (
                  <>
                    <div>
                      <label className="block text-sm font-medium text-secondary mb-2">
                        Lender Business *
                      </label>
                      <select
                        value={newLoan.lenderBusinessId}
                        onChange={(e) => setNewLoan({...newLoan, lenderBusinessId: e.target.value})}
                        className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-primary focus:outline-none focus:ring-2 focus:ring-blue-500"
                        required
                      >
                        <option value="">Select lender business</option>
                        {businesses.filter(business => business.isUserBusiness).map(business => (
                          <option key={business.id} value={business.id}>
                            {business.name} ({business.type}){business.isUmbrellaBusiness ? ' - Umbrella' : ''}
                          </option>
                        ))}
                      </select>
                    </div>

                    {/* Lender Business Balance Display */}
                    {newLoan.lenderBusinessId && (
                      <BusinessBalanceDisplay
                        businessId={newLoan.lenderBusinessId}
                        businessName={businesses.find(b => b.id === newLoan.lenderBusinessId)?.name || 'Selected Business'}
                        showRefreshButton={true}
                        variant="compact"
                      />
                    )}
                  </>
                ) : (
                  <div>
                    <label className="block text-sm font-medium text-secondary mb-2">
                      External Lender *
                    </label>
                    <select
                      value={newLoan.lenderPersonId}
                      onChange={(e) => setNewLoan({...newLoan, lenderPersonId: e.target.value})}
                      className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-primary focus:outline-none focus:ring-2 focus:ring-blue-500"
                      required
                    >
                      <option value="">Select lender</option>
                      {lenders.map(lender => (
                        <option key={lender.id} value={lender.id}>
                          {lender.displayName}
                        </option>
                      ))}
                    </select>
                    <div className="mt-2 space-y-1">
                      <p className="text-xs text-gray-600 dark:text-gray-400">
                        💡 External lenders (individuals/banks) manage their own funds. No balance validation required.
                      </p>
                      <p className="text-xs text-blue-600 dark:text-blue-400">
                        Don&apos;t see your lender?{' '}
                        <button
                          type="button"
                          onClick={() => setShowQuickLenderModal(true)}
                          className="underline font-medium hover:text-blue-800 dark:hover:text-blue-300"
                        >
                          Create a new lender
                        </button>
                      </p>
                    </div>
                  </div>
                )}

                {/* Borrower Type Selection */}
                <div>
                  <label className="block text-sm font-medium text-secondary mb-2">
                    Borrower Type *
                  </label>
                  <div className="flex gap-4">
                    <label className="flex items-center">
                      <input
                        type="radio"
                        name="borrowerType"
                        value="business"
                        checked={newLoan.borrowerType === 'business'}
                        onChange={(e) => setNewLoan({
                          ...newLoan,
                          borrowerType: 'business',
                          borrowerPersonId: '',
                          borrowerBusinessId: ''
                        })}
                        className="mr-2"
                      />
                      🏢 Business
                    </label>
                    <label className="flex items-center">
                      <input
                        type="radio"
                        name="borrowerType"
                        value="person"
                        checked={newLoan.borrowerType === 'person'}
                        onChange={(e) => setNewLoan({
                          ...newLoan,
                          borrowerType: 'person',
                          borrowerBusinessId: '',
                          borrowerPersonId: ''
                        })}
                        className="mr-2"
                      />
                      👤 Individual
                    </label>
                  </div>
                  <p className="mt-2 text-xs text-gray-600 dark:text-gray-400">
                    💡 <strong>Business borrower:</strong> Loan repayments will deduct from business balance.
                    <strong className="ml-2">Individual borrower:</strong> Repayments tracked separately (no business balance impact).
                  </p>
                </div>

                {/* Borrower Selection */}
                {newLoan.borrowerType === 'business' ? (
                  <div>
                    <label className="block text-sm font-medium text-secondary mb-2">
                      Borrower Business *
                    </label>
                    <select
                      value={newLoan.borrowerBusinessId}
                      onChange={(e) => setNewLoan({...newLoan, borrowerBusinessId: e.target.value})}
                      className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-primary focus:outline-none focus:ring-2 focus:ring-blue-500"
                      required
                    >
                      <option value="">Select borrower business</option>
                      {businesses.map(business => (
                        <option
                          key={business.id}
                          value={business.id}
                          disabled={newLoan.lenderType === 'business' && business.id === newLoan.lenderBusinessId}
                        >
                          {business.name} ({business.type})
                          {business.isUserBusiness ? ' - Your Business' : ' - External'}
                          {business.isUmbrellaBusiness ? ' - Umbrella' : ''}
                        </option>
                      ))}
                    </select>
                  </div>
                ) : (
                  <div>
                    <label className="block text-sm font-medium text-secondary mb-2">
                      Borrower (Individual) *
                    </label>
                    <select
                      value={newLoan.borrowerPersonId}
                      onChange={(e) => setNewLoan({...newLoan, borrowerPersonId: e.target.value})}
                      className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-primary focus:outline-none focus:ring-2 focus:ring-blue-500"
                      required
                    >
                      <option value="">Select borrower</option>
                      {lenders.map(lender => (
                        <option key={lender.id} value={lender.id}>
                          {lender.name}
                        </option>
                      ))}
                    </select>
                  </div>
                )}

                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-secondary mb-2">
                      Principal Amount ($) *
                    </label>
                    <input
                      type="number"
                      step="0.01"
                      min="0.01"
                      value={newLoan.principalAmount}
                      onChange={(e) => setNewLoan({...newLoan, principalAmount: e.target.value})}
                      className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-primary focus:outline-none focus:ring-2 focus:ring-blue-500"
                      placeholder="0.00"
                      required
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-secondary mb-2">
                      Interest Rate (%)
                    </label>
                    <input
                      type="number"
                      step="0.1"
                      min="0"
                      max="100"
                      value={newLoan.interestRate}
                      onChange={(e) => setNewLoan({...newLoan, interestRate: e.target.value})}
                      className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-primary focus:outline-none focus:ring-2 focus:ring-blue-500"
                      placeholder="0.0"
                    />
                  </div>
                </div>

                {/* Loan Amount Validation */}
                {loanValidation && (
                  <BalanceValidationWarning
                    validation={loanValidation}
                    businessName={businesses.find(b => b.id === newLoan.lenderBusinessId)?.name || 'Lender Business'}
                    transactionType="loan"
                  />
                )}

                <div>
                  <label className="block text-sm font-medium text-secondary mb-2">
                    Payment Terms
                  </label>
                  <textarea
                    value={newLoan.terms}
                    onChange={(e) => setNewLoan({...newLoan, terms: e.target.value})}
                    className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-primary focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="e.g., Monthly payments, due in 6 months..."
                    rows={2}
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-secondary mb-2">
                    Notes
                  </label>
                  <textarea
                    value={newLoan.notes}
                    onChange={(e) => setNewLoan({...newLoan, notes: e.target.value})}
                    className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-primary focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="Additional notes or agreements..."
                    rows={2}
                  />
                </div>

                <div className="flex justify-end space-x-3">
                  <button
                    type="button"
                    onClick={() => setShowCreateLoanModal(false)}
                    className="px-4 py-2 text-sm font-medium text-secondary bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-md hover:bg-gray-50 dark:hover:bg-gray-600"
                  >
                    Cancel
                  </button>
                  <button
                    type="submit"
                    disabled={loanValidation && !loanValidation.isValid}
                    className={`px-4 py-2 text-sm font-medium border border-transparent rounded-md ${
                      loanValidation && !loanValidation.isValid
                        ? 'text-gray-400 bg-gray-300 dark:bg-gray-600 dark:text-gray-500 cursor-not-allowed'
                        : 'text-white bg-blue-600 hover:bg-blue-700'
                    }`}
                  >
                    {loanValidation && !loanValidation.isValid ? 'Insufficient Funds' : 'Create Loan'}
                  </button>
                </div>
              </form>
            </div>
          </div>
        )}

        {/* Loan Details Modal */}
        {showLoanDetailsModal && selectedLoan && (
          <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
            <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-xl max-w-2xl w-full mx-4 max-h-[80vh] overflow-y-auto">
              <div className="flex justify-between items-start mb-4">
                <h2 className="text-xl font-semibold text-primary">Loan Details - {selectedLoan.loanNumber}</h2>
                <button
                  onClick={() => setShowLoanDetailsModal(false)}
                  className="text-gray-400 hover:text-gray-600 dark:text-gray-500 dark:hover:text-gray-300"
                >
                  ✕
                </button>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
                <div className="space-y-4">
                  <div>
                    <label className="block text-sm font-medium text-secondary">Principal Amount</label>
                    <p className="text-lg font-semibold text-primary">${selectedLoan.principalAmount.toFixed(2)}</p>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-secondary">Remaining Balance</label>
                    <p className="text-lg font-semibold text-orange-600">${selectedLoan.remainingBalance.toFixed(2)}</p>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-secondary">Interest Rate</label>
                    <p className="text-lg font-semibold text-primary">{selectedLoan.interestRate}%</p>
                  </div>
                </div>

                <div className="space-y-4">
                  <div>
                    <label className="block text-sm font-medium text-secondary">Status</label>
                    <span className={`px-2 py-1 text-xs font-medium rounded ${
                      selectedLoan.status === 'active' 
                        ? 'bg-green-100 text-green-800' 
                        : selectedLoan.status === 'paid'
                        ? 'bg-gray-100 text-gray-800'
                        : 'bg-red-100 text-red-800'
                    }`}>
                      {selectedLoan.status.charAt(0).toUpperCase() + selectedLoan.status.slice(1)}
                    </span>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-secondary">Loan Date</label>
                    <p className="text-primary">{formatDate(selectedLoan.loanDate)}</p>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-secondary">Lender → Borrower</label>
                    <p className="text-primary">
                      {selectedLoan.lenderType === 'person'
                        ? (selectedLoan.persons_lender?.fullName || 'External Lender')
                        : (selectedLoan.lenderBusiness?.name || 'Your Business')}
                      {' → '}
                      {selectedLoan.borrowerType === 'person'
                        ? (selectedLoan.persons_borrower?.fullName || 'Individual')
                        : (selectedLoan.borrowerBusiness?.name || 'Unknown')}
                    </p>
                  </div>
                </div>
              </div>

              {selectedLoan.terms && (
                <div className="mb-6">
                  <label className="block text-sm font-medium text-secondary mb-2">Payment Terms</label>
                  <p className="text-primary bg-gray-50 dark:bg-gray-700 p-3 rounded">{selectedLoan.terms}</p>
                </div>
              )}

              {selectedLoan.notes && (
                <div className="mb-6">
                  <label className="block text-sm font-medium text-secondary mb-2">Notes</label>
                  <p className="text-primary bg-gray-50 dark:bg-gray-700 p-3 rounded">{selectedLoan.notes}</p>
                </div>
              )}

              {/* Transaction History */}
              <div>
                <h3 className="text-lg font-semibold text-primary mb-4">Transaction History</h3>
                {selectedLoan.loanTransactions.length === 0 ? (
                  <p className="text-secondary">No transactions yet.</p>
                ) : (
                  <div className="overflow-x-auto">
                    <table className="w-full text-sm">
                      <thead className="bg-gray-50 dark:bg-gray-700">
                        <tr>
                          <th className="px-3 py-2 text-left text-xs font-medium text-secondary uppercase">Date</th>
                          <th className="px-3 py-2 text-left text-xs font-medium text-secondary uppercase">Type</th>
                          <th className="px-3 py-2 text-left text-xs font-medium text-secondary uppercase">Amount</th>
                          <th className="px-3 py-2 text-left text-xs font-medium text-secondary uppercase">Description</th>
                          <th className="px-3 py-2 text-left text-xs font-medium text-secondary uppercase">Source</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-gray-200 dark:divide-gray-700">
                        {selectedLoan.loanTransactions.map(transaction => (
                          <tr key={transaction.id}>
                            <td className="px-3 py-2 text-primary">
                              {formatDate(transaction.transactionDate)}
                            </td>
                            <td className="px-3 py-2">
                              <span className={`px-2 py-1 text-xs font-medium rounded ${
                                transaction.transactionType === 'payment' 
                                  ? 'bg-green-100 text-green-800'
                                  : 'bg-blue-100 text-blue-800'
                              }`}>
                                {transaction.transactionType === 'payment' ? 'Payment' : 'Advance'}
                              </span>
                            </td>
                            <td className="px-3 py-2 font-medium text-primary">
                              ${transaction.amount.toFixed(2)}
                            </td>
                            <td className="px-3 py-2 text-primary">{transaction.description}</td>
                            <td className="px-3 py-2">
                              <span className={`px-2 py-1 text-xs font-medium rounded ${
                                transaction.isAutoGenerated 
                                  ? 'bg-purple-100 text-purple-800'
                                  : 'bg-gray-100 text-gray-800'
                              }`}>
                                {transaction.isAutoGenerated ? 'Auto' : 'Manual'}
                              </span>
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                )}
              </div>
            </div>
          </div>
        )}

        {/* Payment Modal */}
        {showPaymentModal && selectedLoan && (
          <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
            <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-xl max-w-md w-full mx-4">
              <div className="flex justify-between items-start mb-4">
                <h2 className="text-xl font-semibold text-primary">Make Payment - {selectedLoan.loanNumber}</h2>
                <button
                  onClick={() => setShowPaymentModal(false)}
                  className="text-gray-400 hover:text-gray-600 dark:text-gray-500 dark:hover:text-gray-300"
                >
                  ✕
                </button>
              </div>

              <div className="mb-4 p-4 bg-blue-50 dark:bg-blue-900/20 rounded-lg">
                <div className="text-sm text-secondary space-y-1">
                  <div>
                    <strong>Lender → Borrower:</strong>{' '}
                    {selectedLoan.lenderType === 'person'
                      ? (selectedLoan.persons_lender?.fullName || 'External Lender')
                      : (selectedLoan.lenderBusiness?.name || 'Your Business')}
                    {' → '}
                    {selectedLoan.borrowerType === 'person'
                      ? (selectedLoan.persons_borrower?.fullName || 'Individual')
                      : (selectedLoan.borrowerBusiness?.name || 'Unknown')}
                  </div>
                  <div><strong>Current Balance:</strong> ${selectedLoan.remainingBalance.toFixed(2)}</div>
                  <div><strong>Interest Rate:</strong> {selectedLoan.interestRate}%</div>
                </div>
              </div>

              {/* Business Balance Display for Payment */}
              {getPaymentBusinessId() && (
                <BusinessBalanceDisplay
                  businessId={getPaymentBusinessId()}
                  businessName={
                    newPayment.transactionType === 'payment'
                      ? selectedLoan?.borrowerBusiness.name || 'Borrower Business'
                      : selectedLoan?.lenderBusiness?.name || 'Lender Business'
                  }
                  showRefreshButton={true}
                  variant="compact"
                  className="mb-4"
                />
              )}

              <form onSubmit={handleMakePayment} className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-secondary mb-3">
                    Transaction Type *
                  </label>
                  <div className="flex gap-4">
                    <label className="flex items-center">
                      <input
                        type="radio"
                        name="paymentType"
                        value="payment"
                        checked={newPayment.transactionType === 'payment'}
                        onChange={(e) => setNewPayment({...newPayment, transactionType: e.target.value})}
                        className="mr-2"
                      />
                      Payment (reduce balance)
                    </label>
                    <label className="flex items-center">
                      <input
                        type="radio"
                        name="paymentType"
                        value="advance"
                        checked={newPayment.transactionType === 'advance'}
                        onChange={(e) => setNewPayment({...newPayment, transactionType: e.target.value})}
                        className="mr-2"
                      />
                      Additional Advance
                    </label>
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-secondary mb-2">
                      Amount ($) *
                    </label>
                    <input
                      type="number"
                      step="0.01"
                      min="0.01"
                      max={newPayment.transactionType === 'payment' ? selectedLoan.remainingBalance : undefined}
                      value={newPayment.amount}
                      onChange={(e) => setNewPayment({...newPayment, amount: e.target.value})}
                      className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-primary focus:outline-none focus:ring-2 focus:ring-blue-500"
                      placeholder="0.00"
                      required
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-secondary mb-2">
                      Date *
                    </label>
                    <input
                      type="date"
                      value={newPayment.transactionDate}
                      onChange={(e) => setNewPayment({...newPayment, transactionDate: e.target.value})}
                      className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-primary focus:outline-none focus:ring-2 focus:ring-blue-500"
                      required
                    />
                  </div>
                </div>

                <div>
                  <label className="block text-sm font-medium text-secondary mb-2">
                    Description *
                  </label>
                  <input
                    type="text"
                    value={newPayment.description}
                    onChange={(e) => setNewPayment({...newPayment, description: e.target.value})}
                    className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-primary focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="Payment description..."
                    required
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-secondary mb-2">
                    Notes
                  </label>
                  <textarea
                    value={newPayment.notes}
                    onChange={(e) => setNewPayment({...newPayment, notes: e.target.value})}
                    className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-primary focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="Additional notes..."
                    rows={2}
                  />
                </div>

                {/* Payment Amount Validation */}
                {paymentValidation && (
                  <BalanceValidationWarning
                    validation={paymentValidation}
                    businessName={
                      newPayment.transactionType === 'payment'
                        ? selectedLoan?.borrowerBusiness.name || 'Borrower Business'
                        : selectedLoan?.lenderBusiness?.name || 'Lender Business'
                    }
                    transactionType={newPayment.transactionType === 'payment' ? 'payment' : 'advance'}
                  />
                )}

                <div className="flex justify-end space-x-3">
                  <button
                    type="button"
                    onClick={() => setShowPaymentModal(false)}
                    className="px-4 py-2 text-sm font-medium text-secondary bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-md hover:bg-gray-50 dark:hover:bg-gray-600"
                  >
                    Cancel
                  </button>
                  <button
                    type="submit"
                    disabled={paymentValidation && !paymentValidation.isValid}
                    className={`px-4 py-2 text-sm font-medium border border-transparent rounded-md ${
                      paymentValidation && !paymentValidation.isValid
                        ? 'text-gray-400 bg-gray-300 dark:bg-gray-600 dark:text-gray-500 cursor-not-allowed'
                        : 'text-white bg-green-600 hover:bg-green-700'
                    }`}
                  >
                    {paymentValidation && !paymentValidation.isValid
                      ? 'Insufficient Funds'
                      : `Process ${newPayment.transactionType === 'payment' ? 'Payment' : 'Advance'}`}
                  </button>
                </div>
              </form>
            </div>
          </div>
        )}

        {/* Quick Lender Creation Modal */}
        {showQuickLenderModal && (
          <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-[60]">
            <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-xl max-w-md w-full mx-4 max-h-[90vh] overflow-y-auto">
              <div className="flex justify-between items-start mb-4">
                <h2 className="text-xl font-semibold text-primary">Quick Add Lender</h2>
                <button
                  onClick={() => setShowQuickLenderModal(false)}
                  className="text-gray-400 hover:text-gray-600 dark:text-gray-500 dark:hover:text-gray-300"
                >
                  ✕
                </button>
              </div>

              <form onSubmit={handleQuickLenderCreate} className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-secondary mb-2">Lender Type *</label>
                  <div className="flex gap-4">
                    <label className="flex items-center">
                      <input
                        type="radio"
                        name="quickLenderType"
                        value="individual"
                        checked={quickLender.lenderType === 'individual'}
                        onChange={() => setQuickLender({...quickLender, lenderType: 'individual'})}
                        className="mr-2"
                      />
                      👤 Individual
                    </label>
                    <label className="flex items-center">
                      <input
                        type="radio"
                        name="quickLenderType"
                        value="bank"
                        checked={quickLender.lenderType === 'bank'}
                        onChange={() => setQuickLender({...quickLender, lenderType: 'bank'})}
                        className="mr-2"
                      />
                      🏦 Bank
                    </label>
                  </div>
                </div>

                <div>
                  <label className="block text-sm font-medium text-secondary mb-2">
                    {quickLender.lenderType === 'bank' ? 'Bank Name' : 'Full Name'} *
                  </label>
                  <input
                    type="text"
                    value={quickLender.fullName}
                    onChange={(e) => setQuickLender({...quickLender, fullName: e.target.value})}
                    className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-primary focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder={quickLender.lenderType === 'bank' ? 'ZB Bank' : 'John Doe'}
                    required
                  />
                </div>

                <PhoneNumberInput
                  value={quickLender.phone}
                  onChange={(fullPhone) => setQuickLender({...quickLender, phone: fullPhone})}
                  label="Phone"
                  required
                />

                {quickLender.lenderType === 'individual' ? (
                  <NationalIdInput
                    value={quickLender.nationalId}
                    templateId={quickLender.nationalIdTemplateId}
                    onChange={(nationalId, templateId) => setQuickLender({...quickLender, nationalId, nationalIdTemplateId: templateId || ''})}
                    label="National ID"
                    required
                  />
                ) : (
                  <>
                    <div>
                      <label className="block text-sm font-medium text-secondary mb-2">Bank Registration No *</label>
                      <input
                        type="text"
                        value={quickLender.bankRegistrationNo}
                        onChange={(e) => setQuickLender({...quickLender, bankRegistrationNo: e.target.value})}
                        className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-primary focus:outline-none focus:ring-2 focus:ring-blue-500"
                        placeholder="REG123456"
                        required
                      />
                    </div>
                    <div className="grid grid-cols-2 gap-3">
                      <div>
                        <label className="block text-sm font-medium text-secondary mb-2">City *</label>
                        <input
                          type="text"
                          value={quickLender.city}
                          onChange={(e) => setQuickLender({...quickLender, city: e.target.value})}
                          className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-primary focus:outline-none focus:ring-2 focus:ring-blue-500"
                          placeholder="Harare"
                          required
                        />
                      </div>
                      <div>
                        <label className="block text-sm font-medium text-secondary mb-2">Country *</label>
                        <input
                          type="text"
                          value={quickLender.country}
                          onChange={(e) => setQuickLender({...quickLender, country: e.target.value})}
                          className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-primary focus:outline-none focus:ring-2 focus:ring-blue-500"
                          placeholder="Zimbabwe"
                          required
                        />
                      </div>
                    </div>
                  </>
                )}

                <div>
                  <label className="block text-sm font-medium text-secondary mb-2">
                    Address {quickLender.lenderType === 'bank' ? '*' : ''}
                  </label>
                  <input
                    type="text"
                    value={quickLender.address}
                    onChange={(e) => setQuickLender({...quickLender, address: e.target.value})}
                    className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-primary focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="123 Main St"
                    required={quickLender.lenderType === 'bank'}
                  />
                </div>

                <div className="flex justify-end space-x-3 pt-2">
                  <button
                    type="button"
                    onClick={() => setShowQuickLenderModal(false)}
                    className="px-4 py-2 text-sm font-medium text-secondary bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-md hover:bg-gray-50 dark:hover:bg-gray-600"
                  >
                    Cancel
                  </button>
                  <button
                    type="submit"
                    className="px-4 py-2 text-sm font-medium text-white bg-blue-600 border border-transparent rounded-md hover:bg-blue-700"
                  >
                    Create & Select
                  </button>
                </div>
              </form>
            </div>
          </div>
        )}
      </ContentLayout>
    </BusinessProtectedRoute>
  )
}