import { updateExpenseAccountBalanceTx } from '@/lib/expense-account-utils'

/**
 * Approve a petty cash request within a Prisma transaction.
 *
 * Called from:
 *   - /api/petty-cash/requests/[requestId]/approve  (normal approval, creates bucket entry)
 *   - /api/expense-account/reverse-to-petty-cash    (reversal, skipBucketEntry = true)
 *
 * @param tx              Prisma transaction client
 * @param requestId       PettyCashRequests.id
 * @param amount          Amount to approve (must be <= requestedAmount)
 * @param approverId      Users.id of the approver
 * @param skipBucketEntry When true, skip creating a CashBucketEntry (cash already left the bucket via original payments)
 */
export async function approvePettyCashInTx(
  tx: any,
  requestId: string,
  amount: number,
  approverId: string,
  skipBucketEntry: boolean = false,
  signatureData?: string
): Promise<{ depositId: string }> {
  const pcRequest = await tx.pettyCashRequests.findUnique({ where: { id: requestId } })
  if (!pcRequest) throw new Error(`Petty cash request ${requestId} not found`)
  if (pcRequest.status !== 'PENDING') {
    throw new Error(`Cannot approve a petty cash request with status ${pcRequest.status}`)
  }

  const now = new Date()

  // 1. Create deposit into expense account
  const deposit = await tx.expenseAccountDeposits.create({
    data: {
      expenseAccountId: pcRequest.expenseAccountId,
      sourceType: 'PETTY_CASH',
      sourceBusinessId: pcRequest.businessId,
      amount,
      depositDate: now,
      autoGeneratedNote: `Petty cash: ${pcRequest.purpose}`,
      createdBy: approverId,
    },
  })

  // 2. Recalculate expense account balance
  await updateExpenseAccountBalanceTx(tx, pcRequest.expenseAccountId)

  // 3. Create cash bucket outflow (unless caller signals cash already left)
  if (!skipBucketEntry) {
    const isEcocash = pcRequest.paymentChannel === 'ECOCASH'
    if (!isEcocash) {
      await tx.cashBucketEntry.create({
        data: {
          businessId: pcRequest.businessId,
          entryType: 'PETTY_CASH',
          direction: 'OUTFLOW',
          amount,
          paymentChannel: 'CASH',
          referenceType: 'PETTY_CASH',
          referenceId: requestId,
          notes: pcRequest.purpose,
          entryDate: now,
          createdBy: approverId,
        },
      })
    }
  }

  // 4. Update petty cash request to APPROVED
  await tx.pettyCashRequests.update({
    where: { id: requestId },
    data: {
      status: 'APPROVED',
      approvedBy: approverId,
      approvedAmount: amount,
      approvedAt: now,
      depositId: deposit.id,
      ...(signatureData ? { signatureData } : {}),
    },
  })

  return { depositId: deposit.id }
}
