import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { getServerUser } from '@/lib/get-server-user'
import { getEffectivePermissions } from '@/lib/permission-utils'
import { updateExpenseAccountBalanceTx } from '@/lib/expense-account-utils'

/**
 * POST /api/restaurant/meal-program/approve
 *
 * Cashier approves a MEAL_BATCH payment request.
 * - Creates a deposit (credit) equal to the batch total — offsets the meal debits
 * - Marks the MEAL_BATCH payment as PAID
 * - Auto-marks all individual MEAL_PROGRAM payments linked to this batch as PAID
 * - No cash bucket movement — money stays earmarked in bucket backing the expense account
 * - Net balance impact: zero (deposit cancels the PAID batch)
 */
export async function POST(request: NextRequest) {
  try {
    const user = await getServerUser()
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const permissions = getEffectivePermissions(user)
    if (!permissions.canSubmitPaymentBatch && user.role !== 'admin') {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
    }

    const body = await request.json()
    const { batchPaymentId } = body
    if (!batchPaymentId) {
      return NextResponse.json({ error: 'batchPaymentId is required' }, { status: 400 })
    }

    // Fetch the MEAL_BATCH payment
    const batchPayment = await prisma.expenseAccountPayments.findUnique({
      where: { id: batchPaymentId },
      select: { id: true, expenseAccountId: true, amount: true, status: true, paymentType: true },
    })
    if (!batchPayment) {
      return NextResponse.json({ error: 'Batch payment not found' }, { status: 404 })
    }
    if (batchPayment.paymentType !== 'MEAL_BATCH') {
      return NextResponse.json({ error: 'Payment is not a MEAL_BATCH' }, { status: 400 })
    }
    if (batchPayment.status !== 'QUEUED') {
      return NextResponse.json({ error: `Batch is already ${batchPayment.status}` }, { status: 400 })
    }

    const expenseAccountId = batchPayment.expenseAccountId
    const totalAmount = Number(batchPayment.amount)

    // Find all individual MEAL_PROGRAM payments linked to this batch
    const individualIds = await prisma.expenseAccountPayments.findMany({
      where: { eodMealBatchId: batchPaymentId },
      select: { id: true },
    })

    await prisma.$transaction(async (tx) => {
      // 1. Create a deposit to credit the expense account (offsets the batch debit)
      await tx.expenseAccountDeposits.create({
        data: {
          expenseAccountId,
          sourceType: 'MEAL_PROGRAM',
          amount: totalAmount,
          depositDate: new Date(),
          autoGeneratedNote: `Meal program cashier approval — batch ${batchPaymentId.slice(0, 8)}`,
          transactionType: 'MEAL_PROGRAM_APPROVAL',
          createdBy: user.id,
        },
      })

      // 2. Mark the MEAL_BATCH payment as PAID
      await tx.expenseAccountPayments.update({
        where: { id: batchPaymentId },
        data: { status: 'PAID', submittedBy: user.id, submittedAt: new Date(), paidAt: new Date() },
      })

      // 3. Auto-mark all linked individual MEAL_PROGRAM payments as PAID
      if (individualIds.length > 0) {
        await tx.expenseAccountPayments.updateMany({
          where: { id: { in: individualIds.map((p) => p.id) } },
          data: { status: 'PAID', submittedBy: user.id, submittedAt: new Date(), paidAt: new Date() },
        })
      }

      // 4. Recalculate balance (net zero: deposit offsets the PAID batch)
      await updateExpenseAccountBalanceTx(tx, expenseAccountId)
    })

    return NextResponse.json({
      success: true,
      approved: individualIds.length,
      totalAmount,
    })
  } catch (error) {
    console.error('Error approving meal program batch:', error)
    return NextResponse.json({ error: 'Failed to approve meal program batch' }, { status: 500 })
  }
}
