import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { getServerUser } from '@/lib/get-server-user'
import { getEffectivePermissions } from '@/lib/permission-utils'
import { updateExpenseAccountBalanceTx } from '@/lib/expense-account-utils'

/**
 * POST /api/restaurant/meal-program/approve
 * Cashier approves all QUEUED MEAL_PROGRAM payments for an expense account.
 * - Creates a deposit (credit) equal to the total subsidy amount
 * - Marks all QUEUED MEAL_PROGRAM payments as PAID
 * - Records a cash bucket INFLOW entry
 * - Net balance impact: zero (deposit = payment)
 */
export async function POST(request: NextRequest) {
  try {
    const user = await getServerUser()
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const permissions = getEffectivePermissions(user)
    if (!permissions.canSubmitPaymentBatch && user.role !== 'admin') {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
    }

    const body = await request.json()
    const { expenseAccountId } = body
    if (!expenseAccountId) {
      return NextResponse.json({ error: 'expenseAccountId is required' }, { status: 400 })
    }

    // Fetch the expense account and its business
    const expenseAccount = await prisma.expenseAccounts.findUnique({
      where: { id: expenseAccountId },
      select: { id: true, businessId: true },
    })
    if (!expenseAccount) {
      return NextResponse.json({ error: 'Expense account not found' }, { status: 404 })
    }

    // Find all QUEUED MEAL_PROGRAM payments for this account
    const pending = await prisma.expenseAccountPayments.findMany({
      where: {
        expenseAccountId,
        status: 'QUEUED',
        paymentType: 'MEAL_PROGRAM',
      },
      select: { id: true, amount: true },
    })

    if (pending.length === 0) {
      return NextResponse.json({ success: true, approved: 0, totalAmount: 0 })
    }

    const totalAmount = pending.reduce((sum, p) => sum + Number(p.amount), 0)
    const paymentIds = pending.map((p) => p.id)

    await prisma.$transaction(async (tx) => {
      // 1. Create a deposit to balance the payments (credit side)
      await tx.expenseAccountDeposits.create({
        data: {
          expenseAccountId,
          sourceType: 'MEAL_PROGRAM',
          amount: totalAmount,
          depositDate: new Date(),
          autoGeneratedNote: `Meal program cashier approval — ${pending.length} subsidy payment${pending.length !== 1 ? 's' : ''}`,
          transactionType: 'MEAL_PROGRAM_APPROVAL',
          createdBy: user.id,
        },
      })

      // 2. Mark all QUEUED MEAL_PROGRAM payments as PAID
      await tx.expenseAccountPayments.updateMany({
        where: { id: { in: paymentIds } },
        data: {
          status: 'PAID',
          submittedBy: user.id,
          submittedAt: new Date(),
        },
      })

      // 3. Record cash bucket INFLOW (represents cash value entering the business for meals served)
      await tx.cashBucketEntry.create({
        data: {
          businessId: expenseAccount.businessId,
          entryType: 'MEAL_PROGRAM',
          direction: 'INFLOW',
          paymentChannel: 'CASH',
          amount: totalAmount,
          referenceType: 'MEAL_PROGRAM_APPROVAL',
          notes: `Meal program — ${pending.length} subsidy payment${pending.length !== 1 ? 's' : ''} approved`,
          entryDate: new Date(),
          createdBy: user.id,
        },
      })

      // 4. Recalculate balance (net zero: deposit + PAID payments cancel out)
      await updateExpenseAccountBalanceTx(tx, expenseAccountId)
    })

    return NextResponse.json({ success: true, approved: pending.length, totalAmount })
  } catch (error) {
    console.error('Error approving meal program payments:', error)
    return NextResponse.json({ error: 'Failed to approve meal program payments' }, { status: 500 })
  }
}
