import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { getServerUser } from '@/lib/get-server-user'
import { isSystemAdmin } from '@/lib/permission-utils'
import { updateExpenseAccountBalanceTx } from '@/lib/expense-account-utils'

async function hasPettyCashApprove(userId: string): Promise<boolean> {
  const record = await prisma.userPermissions.findFirst({
    where: { userId, granted: true, permission: { name: 'petty_cash.approve' } },
  })
  return !!record
}

/**
 * POST /api/petty-cash/requests/[requestId]/approve
 * Cashier approves the request. Atomically:
 *   1. Debits the business account
 *   2. Creates an ExpenseAccountDeposit (PETTY_CASH) into the expense account
 *   3. Updates request status to APPROVED
 * Body: { approvedAmount }
 */
export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ requestId: string }> }
) {
  try {
    const user = await getServerUser()
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    if (!isSystemAdmin(user) && !(await hasPettyCashApprove(user.id))) {
      return NextResponse.json({ error: 'You do not have permission to approve petty cash requests' }, { status: 403 })
    }

    const { requestId } = await params
    const body = await request.json()
    const { approvedAmount } = body

    if (!approvedAmount || Number(approvedAmount) <= 0) {
      return NextResponse.json({ error: 'approvedAmount must be a positive number' }, { status: 400 })
    }

    const pcRequest = await prisma.pettyCashRequests.findUnique({
      where: { id: requestId },
      include: { business: { select: { id: true, name: true } } },
    })

    if (!pcRequest) return NextResponse.json({ error: 'Petty cash request not found' }, { status: 404 })
    if (pcRequest.status !== 'PENDING') {
      return NextResponse.json(
        { error: `Cannot approve a request with status ${pcRequest.status}` },
        { status: 400 }
      )
    }

    const amount = Number(approvedAmount)
    if (amount > Number(pcRequest.requestedAmount)) {
      return NextResponse.json(
        { error: 'approvedAmount cannot exceed the requestedAmount' },
        { status: 400 }
      )
    }

    // Verify business has sufficient balance
    const businessAccount = await prisma.businessAccounts.findUnique({
      where: { businessId: pcRequest.businessId },
    })
    if (!businessAccount) {
      return NextResponse.json({ error: 'Business account not found' }, { status: 404 })
    }
    if (Number(businessAccount.balance) < amount) {
      return NextResponse.json(
        { error: `Insufficient business account balance. Available: $${Number(businessAccount.balance).toFixed(2)}, Required: $${amount.toFixed(2)}` },
        { status: 400 }
      )
    }

    const now = new Date()

    const result = await prisma.$transaction(async (tx: any) => {
      // 1. Debit business account
      const newBusinessBalance = Number(businessAccount.balance) - amount
      await tx.businessAccounts.update({
        where: { businessId: pcRequest.businessId },
        data: { balance: newBusinessBalance },
      })

      const businessTx = await tx.businessTransactions.create({
        data: {
          businessId: pcRequest.businessId,
          type: 'DEBIT',
          amount: -amount,
          description: `Petty cash issued to ${(await prisma.users.findUnique({ where: { id: pcRequest.requestedBy }, select: { name: true } }))?.name || 'requester'}: ${pcRequest.purpose}`,
          balanceAfter: newBusinessBalance,
          createdBy: user.id,
          referenceType: 'PETTY_CASH',
          referenceId: requestId,
        },
      })

      // 2. Deposit into expense account
      const deposit = await tx.expenseAccountDeposits.create({
        data: {
          expenseAccountId: pcRequest.expenseAccountId,
          sourceType: 'PETTY_CASH',
          sourceBusinessId: pcRequest.businessId,
          amount,
          depositDate: now,
          autoGeneratedNote: `Petty cash: ${pcRequest.purpose}`,
          createdBy: user.id,
        },
      })

      // 3. Recalculate expense account balance
      await updateExpenseAccountBalanceTx(tx, pcRequest.expenseAccountId)

      // 4. Update petty cash request
      const updated = await tx.pettyCashRequests.update({
        where: { id: requestId },
        data: {
          status: 'APPROVED',
          approvedBy: user.id,
          approvedAmount: amount,
          approvedAt: now,
          depositId: deposit.id,
          businessTxId: businessTx.id,
        },
        include: {
          business: { select: { id: true, name: true, type: true } },
          expenseAccount: { select: { id: true, accountName: true, accountNumber: true } },
          requester: { select: { id: true, name: true, email: true } },
          approver: { select: { id: true, name: true, email: true } },
        },
      })

      return { updated, businessTxId: businessTx.id, depositId: deposit.id, newBusinessBalance }
    })

    return NextResponse.json({
      success: true,
      message: `Petty cash request approved for $${amount.toFixed(2)}`,
      data: {
        request: {
          id: result.updated.id,
          status: result.updated.status,
          approvedAmount: Number(result.updated.approvedAmount),
          approvedAt: result.updated.approvedAt?.toISOString(),
          approver: result.updated.approver,
          depositId: result.updated.depositId,
          businessTxId: result.updated.businessTxId,
        },
        businessAccountBalance: result.newBusinessBalance,
      },
    })
  } catch (error) {
    console.error('Error approving petty cash request:', error)
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Failed to approve petty cash request' },
      { status: 500 }
    )
  }
}
