/**
 * POST /api/payroll/account/adjust-business-contribution
 *
 * Admin-only: set one business's cumulative EOD payroll contribution (the
 * per-business "Payroll" card on the dashboard's Cash Box Balances widget)
 * to a target value — typically 0 for a clean start, but any value — without
 * deleting the underlying EOD_AUTO_CONTRIBUTION deposit history. Mirrors the
 * global payroll adjust-balance and cash-bucket adjust-balance endpoints'
 * target-balance pattern (see MBM-258/263).
 *
 * The payroll account is one shared global account (businessId: null) —
 * PayrollAccountDeposits.businessId is what makes a deposit attributable to
 * a specific business. A correction is posted as one more deposit row for
 * that businessId, with a signed amount sized to move the business's
 * running total to the target, so it nets into both the per-business
 * dashboard figure and the global account balance without touching prior
 * rows.
 */

import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { getServerUser } from '@/lib/get-server-user'
import { isSystemAdmin } from '@/lib/permission-utils'
import { getGlobalPayrollAccount } from '@/lib/payroll-account-utils'
import { createAuditLog } from '@/lib/audit'

export async function POST(request: NextRequest) {
  try {
    const user = await getServerUser()
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    if (!isSystemAdmin(user)) {
      return NextResponse.json(
        { error: 'Only system administrators can adjust a business\'s payroll contribution' },
        { status: 403 }
      )
    }

    const body = await request.json()
    const { businessId, targetBalance, reason } = body

    if (!businessId) {
      return NextResponse.json({ error: 'businessId is required' }, { status: 400 })
    }
    if (targetBalance === undefined || targetBalance === null || isNaN(Number(targetBalance))) {
      return NextResponse.json({ error: 'targetBalance is required and must be a number' }, { status: 400 })
    }
    if (!reason || !String(reason).trim()) {
      return NextResponse.json({ error: 'A reason is required for a manual adjustment' }, { status: 400 })
    }

    const business = await prisma.businesses.findUnique({ where: { id: businessId }, select: { id: true, name: true } })
    if (!business) {
      return NextResponse.json({ error: 'Business not found' }, { status: 404 })
    }

    const payrollAccount = await getGlobalPayrollAccount()
    if (!payrollAccount) {
      return NextResponse.json({ error: 'Payroll account not found' }, { status: 404 })
    }

    // Same transactionType set the dashboard/history queries sum — includes
    // any prior manual adjustment so re-running this stays idempotent at zero.
    const contributionAgg = await prisma.payrollAccountDeposits.aggregate({
      where: { businessId, transactionType: { in: ['EOD_AUTO_CONTRIBUTION', 'MANUAL_ADJUSTMENT'] } },
      _sum: { amount: true },
    })
    const currentContribution = Number(contributionAgg._sum.amount || 0)
    const target = Math.round(Number(targetBalance) * 100) / 100
    const delta = Math.round((target - currentContribution) * 100) / 100

    if (Math.abs(delta) < 0.01) {
      return NextResponse.json(
        { error: `${business.name}'s payroll contribution already matches the target value — no adjustment needed` },
        { status: 400 }
      )
    }

    const reasonText = String(reason).trim()
    const adjuster = user.name || user.email || user.id

    const newBalance = await prisma.$transaction(async (tx) => {
      await tx.payrollAccountDeposits.create({
        data: {
          payrollAccountId: payrollAccount.id,
          businessId,
          amount: delta,
          depositDate: new Date(),
          transactionType: 'MANUAL_ADJUSTMENT',
          autoGeneratedNote: `Manual balance correction by ${adjuster}: ${currentContribution.toFixed(2)} -> ${target.toFixed(2)}. Reason: ${reasonText}`,
          createdBy: user.id,
        },
      })

      const [depositsSum, paymentsSum] = await Promise.all([
        tx.payrollAccountDeposits.aggregate({
          where: { payrollAccountId: payrollAccount.id },
          _sum: { amount: true },
        }),
        tx.payrollAccountPayments.aggregate({
          where: { payrollAccountId: payrollAccount.id },
          _sum: { amount: true },
        }),
      ])
      const recomputed = Number(depositsSum._sum.amount || 0) - Number(paymentsSum._sum.amount || 0)

      await tx.payrollAccounts.update({
        where: { id: payrollAccount.id },
        data: { balance: recomputed, updatedAt: new Date() },
      })

      return recomputed
    })

    await createAuditLog({
      userId: user.id,
      action: 'PAYROLL_BUSINESS_CONTRIBUTION_ADJUSTED',
      entityType: 'PayrollAccount',
      entityId: payrollAccount.id,
      oldValues: { businessContribution: currentContribution },
      newValues: { businessContribution: target },
      metadata: {
        businessId,
        businessName: business.name,
        deltaAmount: delta,
        reason: reasonText,
        newGlobalBalance: newBalance,
      },
      businessId,
    })

    return NextResponse.json({
      success: true,
      message: `${business.name}'s payroll contribution set to $${target.toFixed(2)}`,
      previousContribution: currentContribution,
      newContribution: target,
      deltaAmount: delta,
      newGlobalBalance: newBalance,
    })
  } catch (error) {
    console.error('[Payroll Adjust Business Contribution] POST error:', error)
    return NextResponse.json(
      { error: 'Failed to adjust business contribution', details: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 }
    )
  }
}
