-- MBM-295: Tag System Expansion — seed the exhaustive clothing tag vocabulary
-- (docs/Exhaustive, practical tag list.md), each with its emoji and section group.
--
-- Idempotent: ON CONFLICT ("businessType", "name") DO NOTHING targets the real
-- unique constraint added by the prior migration — safe to re-run, matches the
-- convention already used by this repo's own category-seeding migrations (e.g.
-- 20251127140000_seed_complete_clothing_categories,
-- 20251031200000_seed_default_business_categories).
--
-- Runs automatically as part of `prisma migrate deploy` — no manual script or
-- per-server step needed (unlike MBM-294's category-image import, this has no
-- external image files to worry about, so it is a pure, self-contained data seed).
--
-- 317 tags across 15 groups, all businessId = NULL (system/shared, clothing-scoped).

INSERT INTO "tags" ("id", "businessType", "name", "emoji", "groupLabel", "createdAt")
VALUES
    ('tag_clothing_cotton', 'clothing', 'cotton', '🌿', 'Fabric / Material', NOW()),
    ('tag_clothing_linen', 'clothing', 'linen', '🌾', 'Fabric / Material', NOW()),
    ('tag_clothing_wool', 'clothing', 'wool', '🐑', 'Fabric / Material', NOW()),
    ('tag_clothing_silk', 'clothing', 'silk', '🪡', 'Fabric / Material', NOW()),
    ('tag_clothing_polyester', 'clothing', 'polyester', '♻️', 'Fabric / Material', NOW()),
    ('tag_clothing_rayon', 'clothing', 'rayon', '🧵', 'Fabric / Material', NOW()),
    ('tag_clothing_nylon', 'clothing', 'nylon', '🕸️', 'Fabric / Material', NOW()),
    ('tag_clothing_spandex', 'clothing', 'spandex', '🤸', 'Fabric / Material', NOW()),
    ('tag_clothing_denim', 'clothing', 'denim', '👖', 'Fabric / Material', NOW()),
    ('tag_clothing_leather', 'clothing', 'leather', '🐂', 'Fabric / Material', NOW()),
    ('tag_clothing_suede', 'clothing', 'suede', '🧥', 'Fabric / Material', NOW()),
    ('tag_clothing_velvet', 'clothing', 'velvet', '🎭', 'Fabric / Material', NOW()),
    ('tag_clothing_corduroy', 'clothing', 'corduroy', '🧶', 'Fabric / Material', NOW()),
    ('tag_clothing_fleece', 'clothing', 'fleece', '🧣', 'Fabric / Material', NOW()),
    ('tag_clothing_knit', 'clothing', 'knit', '🧵', 'Fabric / Material', NOW()),
    ('tag_clothing_jersey', 'clothing', 'jersey', '👕', 'Fabric / Material', NOW()),
    ('tag_clothing_chiffon', 'clothing', 'chiffon', '🎀', 'Fabric / Material', NOW()),
    ('tag_clothing_satin', 'clothing', 'satin', '✨', 'Fabric / Material', NOW()),
    ('tag_clothing_lace', 'clothing', 'lace', '🕸️', 'Fabric / Material', NOW()),
    ('tag_clothing_mesh', 'clothing', 'mesh', '🕸️', 'Fabric / Material', NOW()),
    ('tag_clothing_faux_leather', 'clothing', 'faux-leather', '🧥', 'Fabric / Material', NOW()),
    ('tag_clothing_faux_fur', 'clothing', 'faux-fur', '🧸', 'Fabric / Material', NOW()),
    ('tag_clothing_organic_cotton', 'clothing', 'organic-cotton', '🌱', 'Fabric / Material', NOW()),
    ('tag_clothing_recycled_polyester', 'clothing', 'recycled-polyester', '♻️', 'Fabric / Material', NOW()),
    ('tag_clothing_bamboo', 'clothing', 'bamboo', '🎋', 'Fabric / Material', NOW()),
    ('tag_clothing_tencel', 'clothing', 'tencel', '🌳', 'Fabric / Material', NOW()),
    ('tag_clothing_cashmere', 'clothing', 'cashmere', '🐐', 'Fabric / Material', NOW()),
    ('tag_clothing_mohair', 'clothing', 'mohair', '🐐', 'Fabric / Material', NOW()),
    ('tag_clothing_acetate', 'clothing', 'acetate', '🧪', 'Fabric / Material', NOW()),
    ('tag_clothing_modal', 'clothing', 'modal', '🌿', 'Fabric / Material', NOW()),
    ('tag_clothing_solid', 'clothing', 'solid', '⬛', 'Pattern / Print', NOW()),
    ('tag_clothing_striped', 'clothing', 'striped', '🟦', 'Pattern / Print', NOW()),
    ('tag_clothing_checkered', 'clothing', 'checkered', '◼️', 'Pattern / Print', NOW()),
    ('tag_clothing_plaid', 'clothing', 'plaid', '🏴', 'Pattern / Print', NOW()),
    ('tag_clothing_gingham', 'clothing', 'gingham', '🧺', 'Pattern / Print', NOW()),
    ('tag_clothing_houndstooth', 'clothing', 'houndstooth', '⬛⬜', 'Pattern / Print', NOW()),
    ('tag_clothing_polka_dot', 'clothing', 'polka-dot', '⚪', 'Pattern / Print', NOW()),
    ('tag_clothing_floral', 'clothing', 'floral', '🌸', 'Pattern / Print', NOW()),
    ('tag_clothing_paisley', 'clothing', 'paisley', '🌀', 'Pattern / Print', NOW()),
    ('tag_clothing_geometric', 'clothing', 'geometric', '🔷', 'Pattern / Print', NOW()),
    ('tag_clothing_animal_print', 'clothing', 'animal-print', '🐆', 'Pattern / Print', NOW()),
    ('tag_clothing_leopard', 'clothing', 'leopard', '🐆', 'Pattern / Print', NOW()),
    ('tag_clothing_zebra', 'clothing', 'zebra', '🦓', 'Pattern / Print', NOW()),
    ('tag_clothing_snake', 'clothing', 'snake', '🐍', 'Pattern / Print', NOW()),
    ('tag_clothing_camo', 'clothing', 'camo', '🪖', 'Pattern / Print', NOW()),
    ('tag_clothing_tie_dye', 'clothing', 'tie-dye', '🌈', 'Pattern / Print', NOW()),
    ('tag_clothing_ombre', 'clothing', 'ombre', '🎨', 'Pattern / Print', NOW()),
    ('tag_clothing_color_block', 'clothing', 'color-block', '🟥🟦', 'Pattern / Print', NOW()),
    ('tag_clothing_graphic', 'clothing', 'graphic', '🖼️', 'Pattern / Print', NOW()),
    ('tag_clothing_logo_print', 'clothing', 'logo-print', '™️', 'Pattern / Print', NOW()),
    ('tag_clothing_cartoon', 'clothing', 'cartoon', '🧸', 'Pattern / Print', NOW()),
    ('tag_clothing_abstract', 'clothing', 'abstract', '🎨', 'Pattern / Print', NOW()),
    ('tag_clothing_paisley_print', 'clothing', 'paisley-print', '🌀', 'Pattern / Print', NOW()),
    ('tag_clothing_argyle', 'clothing', 'argyle', '🔶', 'Pattern / Print', NOW()),
    ('tag_clothing_herringbone', 'clothing', 'herringbone', '🪚', 'Pattern / Print', NOW()),
    ('tag_clothing_jacquard', 'clothing', 'jacquard', '🧵', 'Pattern / Print', NOW()),
    ('tag_clothing_brocade', 'clothing', 'brocade', '🏯', 'Pattern / Print', NOW()),
    ('tag_clothing_embroidered', 'clothing', 'embroidered', '🪡', 'Pattern / Print', NOW()),
    ('tag_clothing_printed', 'clothing', 'printed', '🖨️', 'Pattern / Print', NOW()),
    ('tag_clothing_distressed', 'clothing', 'distressed', '🧱', 'Pattern / Print', NOW()),
    ('tag_clothing_black', 'clothing', 'black', '⬛', 'Color Family (use alongside specific color names)', NOW()),
    ('tag_clothing_white', 'clothing', 'white', '⬜', 'Color Family (use alongside specific color names)', NOW()),
    ('tag_clothing_gray', 'clothing', 'gray', '⬜', 'Color Family (use alongside specific color names)', NOW()),
    ('tag_clothing_navy', 'clothing', 'navy', '🟦', 'Color Family (use alongside specific color names)', NOW()),
    ('tag_clothing_blue', 'clothing', 'blue', '🟦', 'Color Family (use alongside specific color names)', NOW()),
    ('tag_clothing_red', 'clothing', 'red', '🟥', 'Color Family (use alongside specific color names)', NOW()),
    ('tag_clothing_green', 'clothing', 'green', '🟩', 'Color Family (use alongside specific color names)', NOW()),
    ('tag_clothing_olive', 'clothing', 'olive', '🫒', 'Color Family (use alongside specific color names)', NOW()),
    ('tag_clothing_khaki', 'clothing', 'khaki', '🟫', 'Color Family (use alongside specific color names)', NOW()),
    ('tag_clothing_beige', 'clothing', 'beige', '🟫', 'Color Family (use alongside specific color names)', NOW()),
    ('tag_clothing_brown', 'clothing', 'brown', '🟫', 'Color Family (use alongside specific color names)', NOW()),
    ('tag_clothing_tan', 'clothing', 'tan', '🟫', 'Color Family (use alongside specific color names)', NOW()),
    ('tag_clothing_cream', 'clothing', 'cream', '🟨', 'Color Family (use alongside specific color names)', NOW()),
    ('tag_clothing_yellow', 'clothing', 'yellow', '🟨', 'Color Family (use alongside specific color names)', NOW()),
    ('tag_clothing_orange', 'clothing', 'orange', '🟧', 'Color Family (use alongside specific color names)', NOW()),
    ('tag_clothing_pink', 'clothing', 'pink', '🩷', 'Color Family (use alongside specific color names)', NOW()),
    ('tag_clothing_purple', 'clothing', 'purple', '🟪', 'Color Family (use alongside specific color names)', NOW()),
    ('tag_clothing_burgundy', 'clothing', 'burgundy', '🍷', 'Color Family (use alongside specific color names)', NOW()),
    ('tag_clothing_maroon', 'clothing', 'maroon', '🍷', 'Color Family (use alongside specific color names)', NOW()),
    ('tag_clothing_teal', 'clothing', 'teal', '🟦', 'Color Family (use alongside specific color names)', NOW()),
    ('tag_clothing_turquoise', 'clothing', 'turquoise', '🟦', 'Color Family (use alongside specific color names)', NOW()),
    ('tag_clothing_mint', 'clothing', 'mint', '🟩', 'Color Family (use alongside specific color names)', NOW()),
    ('tag_clothing_gold', 'clothing', 'gold', '🏅', 'Color Family (use alongside specific color names)', NOW()),
    ('tag_clothing_silver', 'clothing', 'silver', '🥈', 'Color Family (use alongside specific color names)', NOW()),
    ('tag_clothing_metallic', 'clothing', 'metallic', '✨', 'Color Family (use alongside specific color names)', NOW()),
    ('tag_clothing_pastel', 'clothing', 'pastel', '🌸', 'Color Family (use alongside specific color names)', NOW()),
    ('tag_clothing_neon', 'clothing', 'neon', '🌟', 'Color Family (use alongside specific color names)', NOW()),
    ('tag_clothing_multicolor', 'clothing', 'multicolor', '🌈', 'Color Family (use alongside specific color names)', NOW()),
    ('tag_clothing_tone_on_tone', 'clothing', 'tone-on-tone', '🎨', 'Color Family (use alongside specific color names)', NOW()),
    ('tag_clothing_slim_fit', 'clothing', 'slim-fit', '📏', 'Fit / Silhouette', NOW()),
    ('tag_clothing_regular_fit', 'clothing', 'regular-fit', '✔️', 'Fit / Silhouette', NOW()),
    ('tag_clothing_relaxed_fit', 'clothing', 'relaxed-fit', '🛋️', 'Fit / Silhouette', NOW()),
    ('tag_clothing_loose', 'clothing', 'loose', '🌬️', 'Fit / Silhouette', NOW()),
    ('tag_clothing_oversized', 'clothing', 'oversized', '🧥', 'Fit / Silhouette', NOW()),
    ('tag_clothing_boxy', 'clothing', 'boxy', '📦', 'Fit / Silhouette', NOW()),
    ('tag_clothing_fitted', 'clothing', 'fitted', '✔️', 'Fit / Silhouette', NOW()),
    ('tag_clothing_bodycon', 'clothing', 'bodycon', '🍑', 'Fit / Silhouette', NOW()),
    ('tag_clothing_a_line', 'clothing', 'a-line', '👗', 'Fit / Silhouette', NOW()),
    ('tag_clothing_empire_waist', 'clothing', 'empire-waist', '👗', 'Fit / Silhouette', NOW()),
    ('tag_clothing_high_waisted', 'clothing', 'high-waisted', '🔝', 'Fit / Silhouette', NOW()),
    ('tag_clothing_low_rise', 'clothing', 'low-rise', '🔽', 'Fit / Silhouette', NOW()),
    ('tag_clothing_cropped', 'clothing', 'cropped', '✂️', 'Fit / Silhouette', NOW()),
    ('tag_clothing_longline', 'clothing', 'longline', '📏', 'Fit / Silhouette', NOW()),
    ('tag_clothing_tapered', 'clothing', 'tapered', '〰️', 'Fit / Silhouette', NOW()),
    ('tag_clothing_straight_leg', 'clothing', 'straight-leg', '➖', 'Fit / Silhouette', NOW()),
    ('tag_clothing_bootcut', 'clothing', 'bootcut', '👢', 'Fit / Silhouette', NOW()),
    ('tag_clothing_wide_leg', 'clothing', 'wide-leg', '🦵', 'Fit / Silhouette', NOW()),
    ('tag_clothing_skinny', 'clothing', 'skinny', '📏', 'Fit / Silhouette', NOW()),
    ('tag_clothing_boyfriend', 'clothing', 'boyfriend', '👔', 'Fit / Silhouette', NOW()),
    ('tag_clothing_girlfriend', 'clothing', 'girlfriend', '👖', 'Fit / Silhouette', NOW()),
    ('tag_clothing_cocoon', 'clothing', 'cocoon', '🥚', 'Fit / Silhouette', NOW()),
    ('tag_clothing_balloon', 'clothing', 'balloon', '🎈', 'Fit / Silhouette', NOW()),
    ('tag_clothing_peplum', 'clothing', 'peplum', '🎀', 'Fit / Silhouette', NOW()),
    ('tag_clothing_wrap', 'clothing', 'wrap', '🎁', 'Fit / Silhouette', NOW()),
    ('tag_clothing_shift', 'clothing', 'shift', '👗', 'Fit / Silhouette', NOW()),
    ('tag_clothing_shirt_dress', 'clothing', 'shirt-dress', '👔', 'Fit / Silhouette', NOW()),
    ('tag_clothing_fit_and_flare', 'clothing', 'fit-and-flare', '🎀', 'Fit / Silhouette', NOW()),
    ('tag_clothing_mini', 'clothing', 'mini', '⬇️', 'Length', NOW()),
    ('tag_clothing_midi', 'clothing', 'midi', '➖', 'Length', NOW()),
    ('tag_clothing_maxi', 'clothing', 'maxi', '⬆️', 'Length', NOW()),
    ('tag_clothing_floor_length', 'clothing', 'floor-length', '🌍', 'Length', NOW()),
    ('tag_clothing_ankle_length', 'clothing', 'ankle-length', '🦶', 'Length', NOW()),
    ('tag_clothing_knee_length', 'clothing', 'knee-length', '🦵', 'Length', NOW()),
    ('tag_clothing_above_knee', 'clothing', 'above-knee', '⬆️', 'Length', NOW()),
    ('tag_clothing_below_knee', 'clothing', 'below-knee', '⬇️', 'Length', NOW()),
    ('tag_clothing_short_sleeve', 'clothing', 'short-sleeve', '👕', 'Length', NOW()),
    ('tag_clothing_long_sleeve', 'clothing', 'long-sleeve', '🧥', 'Length', NOW()),
    ('tag_clothing_sleeveless', 'clothing', 'sleeveless', '🎽', 'Length', NOW()),
    ('tag_clothing_cap_sleeve', 'clothing', 'cap-sleeve', '🧢', 'Length', NOW()),
    ('tag_clothing_three_quarter_sleeve', 'clothing', 'three-quarter-sleeve', '¾', 'Length', NOW()),
    ('tag_clothing_crew_neck', 'clothing', 'crew-neck', '⭕', 'Neckline (tops/dresses)', NOW()),
    ('tag_clothing_v_neck', 'clothing', 'v-neck', '🅥', 'Neckline (tops/dresses)', NOW()),
    ('tag_clothing_scoop_neck', 'clothing', 'scoop-neck', '🥣', 'Neckline (tops/dresses)', NOW()),
    ('tag_clothing_boat_neck', 'clothing', 'boat-neck', '⛵', 'Neckline (tops/dresses)', NOW()),
    ('tag_clothing_turtleneck', 'clothing', 'turtleneck', '🐢', 'Neckline (tops/dresses)', NOW()),
    ('tag_clothing_mock_neck', 'clothing', 'mock-neck', '🧣', 'Neckline (tops/dresses)', NOW()),
    ('tag_clothing_halter', 'clothing', 'halter', '🎽', 'Neckline (tops/dresses)', NOW()),
    ('tag_clothing_off_shoulder', 'clothing', 'off-shoulder', '👚', 'Neckline (tops/dresses)', NOW()),
    ('tag_clothing_one_shoulder', 'clothing', 'one-shoulder', '1️⃣', 'Neckline (tops/dresses)', NOW()),
    ('tag_clothing_sweetheart', 'clothing', 'sweetheart', '💖', 'Neckline (tops/dresses)', NOW()),
    ('tag_clothing_square_neck', 'clothing', 'square-neck', '◼️', 'Neckline (tops/dresses)', NOW()),
    ('tag_clothing_keyhole', 'clothing', 'keyhole', '🔑', 'Neckline (tops/dresses)', NOW()),
    ('tag_clothing_cowl_neck', 'clothing', 'cowl-neck', '🌀', 'Neckline (tops/dresses)', NOW()),
    ('tag_clothing_peter_pan_collar', 'clothing', 'peter-pan-collar', '🧒', 'Neckline (tops/dresses)', NOW()),
    ('tag_clothing_bell_sleeve', 'clothing', 'bell-sleeve', '🔔', 'Sleeve Style', NOW()),
    ('tag_clothing_bishop_sleeve', 'clothing', 'bishop-sleeve', '⛪', 'Sleeve Style', NOW()),
    ('tag_clothing_balloon_sleeve', 'clothing', 'balloon-sleeve', '🎈', 'Sleeve Style', NOW()),
    ('tag_clothing_puff_sleeve', 'clothing', 'puff-sleeve', '🎈', 'Sleeve Style', NOW()),
    ('tag_clothing_raglan_sleeve', 'clothing', 'raglan-sleeve', '⚾', 'Sleeve Style', NOW()),
    ('tag_clothing_dolman_sleeve', 'clothing', 'dolman-sleeve', '🦇', 'Sleeve Style', NOW()),
    ('tag_clothing_flutter_sleeve', 'clothing', 'flutter-sleeve', '🦋', 'Sleeve Style', NOW()),
    ('tag_clothing_zipper', 'clothing', 'zipper', '🤐', 'Closure / Details', NOW()),
    ('tag_clothing_button_up', 'clothing', 'button-up', '🔘', 'Closure / Details', NOW()),
    ('tag_clothing_snap_button', 'clothing', 'snap-button', '🔲', 'Closure / Details', NOW()),
    ('tag_clothing_hook_and_eye', 'clothing', 'hook-and-eye', '🔗', 'Closure / Details', NOW()),
    ('tag_clothing_tie_front', 'clothing', 'tie-front', '🎀', 'Closure / Details', NOW()),
    ('tag_clothing_drawstring', 'clothing', 'drawstring', '🪢', 'Closure / Details', NOW()),
    ('tag_clothing_elastic_waist', 'clothing', 'elastic-waist', '🩳', 'Closure / Details', NOW()),
    ('tag_clothing_belt_loop', 'clothing', 'belt-loop', '🪢', 'Closure / Details', NOW()),
    ('tag_clothing_pockets', 'clothing', 'pockets', '🎒', 'Closure / Details', NOW()),
    ('tag_clothing_cargo_pockets', 'clothing', 'cargo-pockets', '🎒', 'Closure / Details', NOW()),
    ('tag_clothing_ruffles', 'clothing', 'ruffles', '🎀', 'Closure / Details', NOW()),
    ('tag_clothing_pleats', 'clothing', 'pleats', '📄', 'Closure / Details', NOW()),
    ('tag_clothing_gathers', 'clothing', 'gathers', '🌼', 'Closure / Details', NOW()),
    ('tag_clothing_darts', 'clothing', 'darts', '📍', 'Closure / Details', NOW()),
    ('tag_clothing_slits', 'clothing', 'slits', '✂️', 'Closure / Details', NOW()),
    ('tag_clothing_cut_out', 'clothing', 'cut-out', '✂️', 'Closure / Details', NOW()),
    ('tag_clothing_lace_up', 'clothing', 'lace-up', '🥾', 'Closure / Details', NOW()),
    ('tag_clothing_buckle', 'clothing', 'buckle', '🪢', 'Closure / Details', NOW()),
    ('tag_clothing_toggle', 'clothing', 'toggle', '🪢', 'Closure / Details', NOW()),
    ('tag_clothing_magnetic_closure', 'clothing', 'magnetic-closure', '🧲', 'Closure / Details', NOW()),
    ('tag_clothing_casual', 'clothing', 'casual', '🏠', 'Occasion / Use Case', NOW()),
    ('tag_clothing_everyday', 'clothing', 'everyday', '📅', 'Occasion / Use Case', NOW()),
    ('tag_clothing_work', 'clothing', 'work', '💼', 'Occasion / Use Case', NOW()),
    ('tag_clothing_office', 'clothing', 'office', '👔', 'Occasion / Use Case', NOW()),
    ('tag_clothing_business_casual', 'clothing', 'business-casual', '👞', 'Occasion / Use Case', NOW()),
    ('tag_clothing_formal', 'clothing', 'formal', '🎩', 'Occasion / Use Case', NOW()),
    ('tag_clothing_cocktail', 'clothing', 'cocktail', '🍸', 'Occasion / Use Case', NOW()),
    ('tag_clothing_evening', 'clothing', 'evening', '🌙', 'Occasion / Use Case', NOW()),
    ('tag_clothing_party', 'clothing', 'party', '🎉', 'Occasion / Use Case', NOW()),
    ('tag_clothing_wedding', 'clothing', 'wedding', '💒', 'Occasion / Use Case', NOW()),
    ('tag_clothing_guest_outfit', 'clothing', 'guest-outfit', '🎁', 'Occasion / Use Case', NOW()),
    ('tag_clothing_date_night', 'clothing', 'date-night', '💕', 'Occasion / Use Case', NOW()),
    ('tag_clothing_night_out', 'clothing', 'night-out', '🌃', 'Occasion / Use Case', NOW()),
    ('tag_clothing_weekend', 'clothing', 'weekend', '🏖️', 'Occasion / Use Case', NOW()),
    ('tag_clothing_travel', 'clothing', 'travel', '✈️', 'Occasion / Use Case', NOW()),
    ('tag_clothing_vacation', 'clothing', 'vacation', '🏝️', 'Occasion / Use Case', NOW()),
    ('tag_clothing_beach', 'clothing', 'beach', '🏖️', 'Occasion / Use Case', NOW()),
    ('tag_clothing_resort', 'clothing', 'resort', '🏨', 'Occasion / Use Case', NOW()),
    ('tag_clothing_outdoor', 'clothing', 'outdoor', '🌲', 'Occasion / Use Case', NOW()),
    ('tag_clothing_hiking', 'clothing', 'hiking', '🥾', 'Occasion / Use Case', NOW()),
    ('tag_clothing_gym', 'clothing', 'gym', '🏋️', 'Occasion / Use Case', NOW()),
    ('tag_clothing_workout', 'clothing', 'workout', '🏃', 'Occasion / Use Case', NOW()),
    ('tag_clothing_running', 'clothing', 'running', '🏃', 'Occasion / Use Case', NOW()),
    ('tag_clothing_yoga', 'clothing', 'yoga', '🧘', 'Occasion / Use Case', NOW()),
    ('tag_clothing_sports', 'clothing', 'sports', '⚽', 'Occasion / Use Case', NOW()),
    ('tag_clothing_lounge', 'clothing', 'lounge', '🛋️', 'Occasion / Use Case', NOW()),
    ('tag_clothing_sleepwear', 'clothing', 'sleepwear', '🌙', 'Occasion / Use Case', NOW()),
    ('tag_clothing_loungewear', 'clothing', 'loungewear', '🧘', 'Occasion / Use Case', NOW()),
    ('tag_clothing_maternity', 'clothing', 'maternity', '🤰', 'Occasion / Use Case', NOW()),
    ('tag_clothing_nursing', 'clothing', 'nursing', '🤱', 'Occasion / Use Case', NOW()),
    ('tag_clothing_school', 'clothing', 'school', '🎒', 'Occasion / Use Case', NOW()),
    ('tag_clothing_uniform', 'clothing', 'uniform', '🪖', 'Occasion / Use Case', NOW()),
    ('tag_clothing_spring', 'clothing', 'spring', '🌸', 'Season / Collection', NOW()),
    ('tag_clothing_summer', 'clothing', 'summer', '☀️', 'Season / Collection', NOW()),
    ('tag_clothing_autumn', 'clothing', 'autumn', '🍂', 'Season / Collection', NOW()),
    ('tag_clothing_winter', 'clothing', 'winter', '❄️', 'Season / Collection', NOW()),
    ('tag_clothing_all_season', 'clothing', 'all-season', '📅', 'Season / Collection', NOW()),
    ('tag_clothing_resort_collection', 'clothing', 'resort-collection', '🏝️', 'Season / Collection', NOW()),
    ('tag_clothing_pre_fall', 'clothing', 'pre-fall', '🍂', 'Season / Collection', NOW()),
    ('tag_clothing_fall_winter', 'clothing', 'fall-winter', '🍂❄️', 'Season / Collection', NOW()),
    ('tag_clothing_spring_summer', 'clothing', 'spring-summer', '🌸☀️', 'Season / Collection', NOW()),
    ('tag_clothing_holiday_collection', 'clothing', 'holiday-collection', '🎄', 'Season / Collection', NOW()),
    ('tag_clothing_cruise_collection', 'clothing', 'cruise-collection', '🚢', 'Season / Collection', NOW()),
    ('tag_clothing_capsule_collection', 'clothing', 'capsule-collection', '🧳', 'Season / Collection', NOW()),
    ('tag_clothing_limited_edition', 'clothing', 'limited-edition', '⭐', 'Season / Collection', NOW()),
    ('tag_clothing_new_arrival', 'clothing', 'new-arrival', '✨', 'Season / Collection', NOW()),
    ('tag_clothing_core_collection', 'clothing', 'core-collection', '📦', 'Season / Collection', NOW()),
    ('tag_clothing_basics', 'clothing', 'basics', '🧱', 'Season / Collection', NOW()),
    ('tag_clothing_women', 'clothing', 'women', '👩', 'Audience / Demographic', NOW()),
    ('tag_clothing_men', 'clothing', 'men', '👨', 'Audience / Demographic', NOW()),
    ('tag_clothing_unisex', 'clothing', 'unisex', '🧑', 'Audience / Demographic', NOW()),
    ('tag_clothing_kids', 'clothing', 'kids', '👶', 'Audience / Demographic', NOW()),
    ('tag_clothing_teens', 'clothing', 'teens', '🧒', 'Audience / Demographic', NOW()),
    ('tag_clothing_plus_size', 'clothing', 'plus-size', '🧍', 'Audience / Demographic', NOW()),
    ('tag_clothing_petite', 'clothing', 'petite', '🤏', 'Audience / Demographic', NOW()),
    ('tag_clothing_tall', 'clothing', 'tall', '📏', 'Audience / Demographic', NOW()),
    ('tag_clothing_seniors', 'clothing', 'seniors', '👴', 'Audience / Demographic', NOW()),
    ('tag_clothing_gender_neutral', 'clothing', 'gender-neutral', '⚧', 'Audience / Demographic', NOW()),
    ('tag_clothing_boys', 'clothing', 'boys', '👦', 'Audience / Demographic', NOW()),
    ('tag_clothing_girls', 'clothing', 'girls', '👧', 'Audience / Demographic', NOW()),
    ('tag_clothing_baby', 'clothing', 'baby', '👶', 'Audience / Demographic', NOW()),
    ('tag_clothing_toddler', 'clothing', 'toddler', '🧒', 'Audience / Demographic', NOW()),
    ('tag_clothing_classic', 'clothing', 'classic', '🕰️', 'Style / Vibe', NOW()),
    ('tag_clothing_minimalist', 'clothing', 'minimalist', '🎯', 'Style / Vibe', NOW()),
    ('tag_clothing_boho', 'clothing', 'boho', '🌼', 'Style / Vibe', NOW()),
    ('tag_clothing_romantic', 'clothing', 'romantic', '🌹', 'Style / Vibe', NOW()),
    ('tag_clothing_chic', 'clothing', 'chic', '💅', 'Style / Vibe', NOW()),
    ('tag_clothing_glam', 'clothing', 'glam', '✨', 'Style / Vibe', NOW()),
    ('tag_clothing_edgy', 'clothing', 'edgy', '⚡', 'Style / Vibe', NOW()),
    ('tag_clothing_streetwear', 'clothing', 'streetwear', '🛹', 'Style / Vibe', NOW()),
    ('tag_clothing_urban', 'clothing', 'urban', '🏙️', 'Style / Vibe', NOW()),
    ('tag_clothing_preppy', 'clothing', 'preppy', '🎓', 'Style / Vibe', NOW()),
    ('tag_clothing_vintage', 'clothing', 'vintage', '🕰️', 'Style / Vibe', NOW()),
    ('tag_clothing_retro', 'clothing', 'retro', '📻', 'Style / Vibe', NOW()),
    ('tag_clothing_sporty', 'clothing', 'sporty', '🏃', 'Style / Vibe', NOW()),
    ('tag_clothing_athleisure', 'clothing', 'athleisure', '🏋️', 'Style / Vibe', NOW()),
    ('tag_clothing_luxury', 'clothing', 'luxury', '💎', 'Style / Vibe', NOW()),
    ('tag_clothing_premium', 'clothing', 'premium', '🌟', 'Style / Vibe', NOW()),
    ('tag_clothing_affordable', 'clothing', 'affordable', '💰', 'Style / Vibe', NOW()),
    ('tag_clothing_sustainable', 'clothing', 'sustainable', '🌱', 'Style / Vibe', NOW()),
    ('tag_clothing_eco_friendly', 'clothing', 'eco-friendly', '🌍', 'Style / Vibe', NOW()),
    ('tag_clothing_ethical_handmade', 'clothing', 'ethical-handmade', '🤲', 'Style / Vibe', NOW()),
    ('tag_clothing_artisan', 'clothing', 'artisan', '🎨', 'Style / Vibe', NOW()),
    ('tag_clothing_designer', 'clothing', 'designer', '🎨', 'Style / Vibe', NOW()),
    ('tag_clothing_fast_fashion', 'clothing', 'fast-fashion', '⚡', 'Style / Vibe', NOW()),
    ('tag_clothing_timeless', 'clothing', 'timeless', '⏳', 'Style / Vibe', NOW()),
    ('tag_clothing_trendy', 'clothing', 'trendy', '📈', 'Style / Vibe', NOW()),
    ('tag_clothing_modest', 'clothing', 'modest', '🧕', 'Style / Vibe', NOW()),
    ('tag_clothing_modest_fashion', 'clothing', 'modest-fashion', '🧕', 'Style / Vibe', NOW()),
    ('tag_clothing_scandinavian', 'clothing', 'scandinavian', '🇸🇪', 'Style / Vibe', NOW()),
    ('tag_clothing_japanese_style', 'clothing', 'japanese-style', '🇯🇵', 'Style / Vibe', NOW()),
    ('tag_clothing_korean_fashion', 'clothing', 'korean-fashion', '🇰🇷', 'Style / Vibe', NOW()),
    ('tag_clothing_organic', 'clothing', 'organic', '🌱', 'Sustainability / Ethics', NOW()),
    ('tag_clothing_recycled', 'clothing', 'recycled', '♻️', 'Sustainability / Ethics', NOW()),
    ('tag_clothing_fair_trade', 'clothing', 'fair-trade', '⚖️', 'Sustainability / Ethics', NOW()),
    ('tag_clothing_ethical', 'clothing', 'ethical', '🤝', 'Sustainability / Ethics', NOW()),
    ('tag_clothing_vegan', 'clothing', 'vegan', '🌱', 'Sustainability / Ethics', NOW()),
    ('tag_clothing_cruelty_free', 'clothing', 'cruelty-free', '🐰', 'Sustainability / Ethics', NOW()),
    ('tag_clothing_low_impact_dye', 'clothing', 'low-impact-dye', '🎨', 'Sustainability / Ethics', NOW()),
    ('tag_clothing_carbon_neutral', 'clothing', 'carbon-neutral', '🌍', 'Sustainability / Ethics', NOW()),
    ('tag_clothing_made_in_usa', 'clothing', 'made-in-usa', '🇺🇸', 'Sustainability / Ethics', NOW()),
    ('tag_clothing_made_in_eu', 'clothing', 'made-in-eu', '🇪🇺', 'Sustainability / Ethics', NOW()),
    ('tag_clothing_locally_made', 'clothing', 'locally-made', '🏘️', 'Sustainability / Ethics', NOW()),
    ('tag_clothing_slow_fashion', 'clothing', 'slow-fashion', '🐌', 'Sustainability / Ethics', NOW()),
    ('tag_clothing_zero_waste', 'clothing', 'zero-waste', '♻️', 'Sustainability / Ethics', NOW()),
    ('tag_clothing_online_only', 'clothing', 'online-only', '🌐', 'Inventory / Operational Tags (internal)', NOW()),
    ('tag_clothing_store_only', 'clothing', 'store-only', '🏪', 'Inventory / Operational Tags (internal)', NOW()),
    ('tag_clothing_omnichannel', 'clothing', 'omnichannel', '🔄', 'Inventory / Operational Tags (internal)', NOW()),
    ('tag_clothing_bestseller', 'clothing', 'bestseller', '🔥', 'Inventory / Operational Tags (internal)', NOW()),
    ('tag_clothing_clearance', 'clothing', 'clearance', '🏷️', 'Inventory / Operational Tags (internal)', NOW()),
    ('tag_clothing_sale', 'clothing', 'sale', '💲', 'Inventory / Operational Tags (internal)', NOW()),
    ('tag_clothing_pre_order', 'clothing', 'pre-order', '📦', 'Inventory / Operational Tags (internal)', NOW()),
    ('tag_clothing_backorder', 'clothing', 'backorder', '⏳', 'Inventory / Operational Tags (internal)', NOW()),
    ('tag_clothing_low_stock', 'clothing', 'low-stock', '⚠️', 'Inventory / Operational Tags (internal)', NOW()),
    ('tag_clothing_out_of_stock', 'clothing', 'out-of-stock', '❌', 'Inventory / Operational Tags (internal)', NOW()),
    ('tag_clothing_restock_soon', 'clothing', 'restock-soon', '🔜', 'Inventory / Operational Tags (internal)', NOW()),
    ('tag_clothing_discontinued', 'clothing', 'discontinued', '🚫', 'Inventory / Operational Tags (internal)', NOW()),
    ('tag_clothing_sample', 'clothing', 'sample', '🧪', 'Inventory / Operational Tags (internal)', NOW()),
    ('tag_clothing_display_only', 'clothing', 'display-only', '🖼️', 'Inventory / Operational Tags (internal)', NOW()),
    ('tag_clothing_damaged', 'clothing', 'damaged', '⚠️', 'Inventory / Operational Tags (internal)', NOW()),
    ('tag_clothing_return', 'clothing', 'return', '🔄', 'Inventory / Operational Tags (internal)', NOW()),
    ('tag_clothing_quality_check', 'clothing', 'quality-check', '✅', 'Inventory / Operational Tags (internal)', NOW()),
    ('tag_clothing_photoshoot', 'clothing', 'photoshoot', '📸', 'Inventory / Operational Tags (internal)', NOW()),
    ('tag_clothing_marketing_hero', 'clothing', 'marketing-hero', '🌟', 'Inventory / Operational Tags (internal)', NOW()),
    ('tag_clothing_primary_image', 'clothing', 'primary-image', '🖼️', 'Inventory / Operational Tags (internal)', NOW()),
    ('tag_clothing_thumbnail', 'clothing', 'thumbnail', '🖼️', 'Inventory / Operational Tags (internal)', NOW()),
    ('tag_clothing_has_inventory', 'clothing', 'has-inventory', '📦', 'Inventory / Operational Tags (internal)', NOW()),
    ('tag_clothing_no_inventory', 'clothing', 'no-inventory', '🚫', 'Inventory / Operational Tags (internal)', NOW()),
    ('tag_clothing_model_shot', 'clothing', 'model-shot', '🧍', 'Image / Media Tags (for your gallery)', NOW()),
    ('tag_clothing_flat_lay', 'clothing', 'flat-lay', '📐', 'Image / Media Tags (for your gallery)', NOW()),
    ('tag_clothing_detail_shot', 'clothing', 'detail-shot', '🔍', 'Image / Media Tags (for your gallery)', NOW()),
    ('tag_clothing_lifestyle', 'clothing', 'lifestyle', '🌆', 'Image / Media Tags (for your gallery)', NOW()),
    ('tag_clothing_on_hanger', 'clothing', 'on-hanger', '🧥', 'Image / Media Tags (for your gallery)', NOW()),
    ('tag_clothing_mannequin', 'clothing', 'mannequin', '🧍', 'Image / Media Tags (for your gallery)', NOW()),
    ('tag_clothing_close_up', 'clothing', 'close-up', '🔎', 'Image / Media Tags (for your gallery)', NOW()),
    ('tag_clothing_back_view', 'clothing', 'back-view', '🔙', 'Image / Media Tags (for your gallery)', NOW()),
    ('tag_clothing_side_view', 'clothing', 'side-view', '➡️', 'Image / Media Tags (for your gallery)', NOW()),
    ('tag_clothing_front_view', 'clothing', 'front-view', '▶️', 'Image / Media Tags (for your gallery)', NOW()),
    ('tag_clothing_action_shot', 'clothing', 'action-shot', '🏃', 'Image / Media Tags (for your gallery)', NOW()),
    ('tag_clothing_editorial', 'clothing', 'editorial', '📰', 'Image / Media Tags (for your gallery)', NOW()),
    ('tag_clothing_campaign', 'clothing', 'campaign', '📣', 'Image / Media Tags (for your gallery)', NOW()),
    ('tag_clothing_ugc', 'clothing', 'ugc', '📱', 'Image / Media Tags (for your gallery)', NOW()),
    ('tag_clothing_influencer_collab', 'clothing', 'influencer-collab', '🤝', 'Image / Media Tags (for your gallery)', NOW()),
    ('tag_clothing_video_available', 'clothing', 'video-available', '🎥', 'Image / Media Tags (for your gallery)', NOW()),
    ('tag_clothing_360_view', 'clothing', '360-view', '🔄', 'Image / Media Tags (for your gallery)', NOW()),
    ('tag_clothing_ar_ready', 'clothing', 'ar-ready', '🕶️', 'Image / Media Tags (for your gallery)', NOW())
ON CONFLICT ("businessType", "name") DO NOTHING;
