import { NextRequest, NextResponse } from 'next/server'
import { Prisma } from '@prisma/client'
import { prisma } from '@/lib/prisma'
import { getServerUser } from '@/lib/get-server-user'
import { getEffectivePermissions } from '@/lib/permission-utils'

type Params = { params: Promise<{ businessId: string }> }

function computeIndicator(balance: number, monthlyRent: number): 'red' | 'orange' | 'green' {
  if (monthlyRent <= 0) return 'red'
  const pct = (balance / monthlyRent) * 100
  if (pct >= 100) return 'green'
  if (pct >= 75) return 'orange'
  return 'red'
}

/**
 * POST /api/rent-account/[businessId]/eod-transfer
 * Create an EOD_RENT_TRANSFER deposit in the rent account.
 * Idempotent: returns existing deposit if one already exists for the given date.
 */
export async function POST(request: NextRequest, { params }: Params) {
  try {
    const user = await getServerUser()
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const { businessId } = await params

    const permissions = getEffectivePermissions(user, businessId)
    const canTransfer =
      user.role === 'admin' ||
      permissions.canManageBusinessSettings ||
      permissions.canMakeExpenseDeposits

    if (!canTransfer) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
    }

    const body = await request.json()
    const { amount, eodDate, note } = body

    if (!amount || Number(amount) <= 0) {
      return NextResponse.json({ error: 'amount must be > 0' }, { status: 400 })
    }
    if (!eodDate) {
      return NextResponse.json({ error: 'eodDate is required (YYYY-MM-DD)' }, { status: 400 })
    }

    // Load rent config
    const config = await prisma.businessRentConfig.findUnique({
      where: { businessId },
      include: {
        expenseAccount: { select: { id: true, balance: true } },
      },
    })

    if (!config) {
      return NextResponse.json({ error: 'No rent account configured for this business' }, { status: 404 })
    }
    if (!config.isActive) {
      return NextResponse.json({ error: 'Rent account is inactive' }, { status: 400 })
    }

    const depositDate = new Date(eodDate)
    const dayStart = new Date(depositDate)
    dayStart.setHours(0, 0, 0, 0)
    const dayEnd = new Date(depositDate)
    dayEnd.setHours(23, 59, 59, 999)

    // Idempotency check: already transferred today?
    const existing = await prisma.expenseAccountDeposits.findFirst({
      where: {
        expenseAccountId: config.expenseAccountId,
        sourceType: 'EOD_RENT_TRANSFER',
        depositDate: { gte: dayStart, lte: dayEnd },
      },
    })

    if (existing) {
      const currentBalance = Number(config.expenseAccount.balance)
      const monthlyRent = Number(config.monthlyRentAmount)
      const fundingPercent = monthlyRent > 0 ? Math.round((currentBalance / monthlyRent) * 1000) / 10 : 0
      return NextResponse.json({
        alreadyTransferred: true,
        deposit: {
          id: existing.id,
          amount: Number(existing.amount),
          depositDate: existing.depositDate,
        },
        newBalance: currentBalance,
        fundingPercent,
        indicator: computeIndicator(currentBalance, monthlyRent),
      })
    }

    // Always round up to nearest whole dollar — no fractional rent deposits
    const transferAmount = Math.ceil(Number(amount))

    // Atomic: balance check + deposit + credit rent account + debit business account + debit transaction
    let deposit: { id: string; amount: Prisma.Decimal; depositDate: Date }
    await prisma.$transaction(async (tx: Prisma.TransactionClient) => {
      // Check business account has sufficient funds
      const bizAcct = await tx.businessAccounts.findUnique({
        where: { businessId },
        select: { balance: true },
      })
      const currentBalance = Number(bizAcct?.balance ?? 0)
      if (currentBalance < transferAmount) {
        throw new Error(`INSUFFICIENT_FUNDS:${currentBalance.toFixed(2)}`)
      }

      deposit = await tx.expenseAccountDeposits.create({
        data: {
          expenseAccountId: config.expenseAccountId,
          sourceType: 'EOD_RENT_TRANSFER',
          sourceBusinessId: businessId,
          amount: transferAmount,
          depositDate,
          autoGeneratedNote: note || `Auto-transfer from EOD close on ${eodDate}`,
          createdBy: user.id,
        },
        select: { id: true, amount: true, depositDate: true },
      })

      await tx.expenseAccounts.update({
        where: { id: config.expenseAccountId },
        data: { balance: { increment: transferAmount }, updatedAt: new Date() },
      })

      await tx.businessAccounts.update({
        where: { businessId },
        data: { balance: { decrement: transferAmount } },
      })

      await tx.businessTransactions.create({
        data: {
          businessId,
          type: 'DEBIT',
          amount: -transferAmount,
          description: `EOD rent transfer → ${config.expenseAccountId}`,
          balanceAfter: currentBalance - transferAmount,
          createdBy: user.id,
          referenceType: 'RENT_TRANSFER',
          referenceId: config.expenseAccountId,
        },
      })
    })

    // Fetch fresh balance
    const updatedAccount = await prisma.expenseAccounts.findUnique({
      where: { id: config.expenseAccountId },
      select: { balance: true },
    })

    const newBalance = Number(updatedAccount!.balance)
    const monthlyRent = Number(config.monthlyRentAmount)
    const fundingPercent = monthlyRent > 0 ? Math.round((newBalance / monthlyRent) * 1000) / 10 : 0

    return NextResponse.json({
      success: true,
      alreadyTransferred: false,
      deposit: {
        id: deposit!.id,
        amount: Number(deposit!.amount),
        depositDate: deposit!.depositDate,
      },
      newBalance,
      fundingPercent,
      indicator: computeIndicator(newBalance, monthlyRent),
    }, { status: 201 })
  } catch (err) {
    console.error('[POST /api/rent-account/eod-transfer]', err)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
