import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import {
  validateDepositAmount,
  validateDepositEdit,
  updateExpenseAccountBalanceTx,
  isWithinEditWindow,
} from '@/lib/expense-account-utils'
import { getEffectivePermissions, isSystemAdmin } from '@/lib/permission-utils'
import { getServerUser } from '@/lib/get-server-user'

/**
 * GET /api/expense-account/[accountId]/deposits/[depositId]
 * Get single deposit details
 */
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ accountId: string; depositId: string }> }
) {
  try {
    const user = await getServerUser()
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // Get user permissions
    const permissions = getEffectivePermissions(user)
    if (!permissions.canAccessExpenseAccount) {
      return NextResponse.json(
        { error: 'You do not have permission to access expense accounts' },
        { status: 403 }
      )
    }

    const { accountId, depositId } = await params

    // Get deposit with relations
    const deposit = await prisma.expenseAccountDeposits.findUnique({
      where: { id: depositId },
      include: {
        expenseAccount: {
          select: {
            id: true,
            accountNumber: true,
            accountName: true,
          },
        },
        sourceBusiness: {
          select: { id: true, name: true, type: true },
        },
        creator: {
          select: { id: true, name: true, email: true },
        },
      },
    })

    if (!deposit) {
      return NextResponse.json({ error: 'Deposit not found' }, { status: 404 })
    }

    // Verify deposit belongs to the specified account
    if (deposit.expenseAccountId !== accountId) {
      return NextResponse.json(
        { error: 'Deposit does not belong to this expense account' },
        { status: 400 }
      )
    }

    return NextResponse.json({
      success: true,
      data: {
        deposit: {
          id: deposit.id,
          expenseAccountId: deposit.expenseAccountId,
          expenseAccount: deposit.expenseAccount,
          sourceType: deposit.sourceType,
          sourceBusinessId: deposit.sourceBusinessId,
          sourceBusiness: deposit.sourceBusiness,
          amount: Number(deposit.amount),
          depositDate: deposit.depositDate.toISOString(),
          autoGeneratedNote: deposit.autoGeneratedNote,
          manualNote: deposit.manualNote,
          transactionType: deposit.transactionType,
          createdBy: deposit.creator,
          createdAt: deposit.createdAt.toISOString(),
        },
      },
    })
  } catch (error) {
    console.error('Error fetching deposit:', error)
    return NextResponse.json(
      { error: 'Failed to fetch deposit' },
      { status: 500 }
    )
  }
}

/**
 * PATCH /api/expense-account/[accountId]/deposits/[depositId]
 * Update deposit details
 */
export async function PATCH(
  request: NextRequest,
  { params }: { params: Promise<{ accountId: string; depositId: string }> }
) {
  try {
    const user = await getServerUser()
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // Get user permissions
    const permissions = getEffectivePermissions(user)
    const isAdmin = isSystemAdmin(user)

    if (!permissions.canEditExpenseTransactions) {
      return NextResponse.json(
        { error: 'You do not have permission to edit expense transactions' },
        { status: 403 }
      )
    }

    const { accountId, depositId } = await params

    // Get existing deposit
    const existingDeposit = await prisma.expenseAccountDeposits.findUnique({
      where: { id: depositId },
      select: {
        id: true,
        amount: true,
        depositDate: true,
        expenseAccountId: true,
        sourceType: true,
        sourceBusinessId: true,
        createdAt: true,
      },
    })

    if (!existingDeposit) {
      return NextResponse.json({ error: 'Deposit not found' }, { status: 404 })
    }

    // Verify deposit belongs to the specified account
    if (existingDeposit.expenseAccountId !== accountId) {
      return NextResponse.json(
        { error: 'Deposit does not belong to this expense account' },
        { status: 400 }
      )
    }

    // Check if within edit window (5 days for non-admins)
    const editWindowCheck = isWithinEditWindow(existingDeposit.createdAt, isAdmin)
    if (!editWindowCheck.allowed) {
      return NextResponse.json(
        { error: editWindowCheck.error },
        { status: 403 }
      )
    }

    // Parse request body
    const body = await request.json()
    const { amount, depositDate, manualNote, transactionType } = body

    // Build update data
    const updateData: any = {}

    // Validate and update amount if provided
    if (amount !== undefined) {
      const amountValidation = validateDepositAmount(Number(amount))
      if (!amountValidation.valid) {
        return NextResponse.json(
          { error: amountValidation.error },
          { status: 400 }
        )
      }

      // Validate that this change won't cause negative balances
      const editValidation = await validateDepositEdit(
        depositId,
        accountId,
        Number(amount)
      )
      if (!editValidation.valid) {
        return NextResponse.json(
          { error: editValidation.error },
          { status: 400 }
        )
      }

      updateData.amount = Number(amount)
    }

    // Validate and update deposit date if provided
    if (depositDate !== undefined) {
      const depDate = new Date(depositDate)
      if (depDate > new Date()) {
        return NextResponse.json(
          { error: 'Deposit date cannot be in the future' },
          { status: 400 }
        )
      }
      updateData.depositDate = depDate
    }

    // Update other fields
    if (manualNote !== undefined) updateData.manualNote = manualNote?.trim() || null
    if (transactionType !== undefined)
      updateData.transactionType = transactionType?.trim() || null

    // Use transaction to update deposit and recalculate balance
    const result = await prisma.$transaction(async (tx) => {
      // Update deposit
      const updatedDeposit = await tx.expenseAccountDeposits.update({
        where: { id: depositId },
        data: updateData,
        include: {
          sourceBusiness: {
            select: { id: true, name: true, type: true },
          },
          creator: {
            select: { id: true, name: true, email: true },
          },
        },
      })

      // Recalculate and update account balance
      const newBalance = await updateExpenseAccountBalanceTx(tx, accountId)

      return { updatedDeposit, newBalance }
    })

    return NextResponse.json({
      success: true,
      message: 'Deposit updated successfully',
      data: {
        deposit: {
          id: result.updatedDeposit.id,
          expenseAccountId: result.updatedDeposit.expenseAccountId,
          sourceType: result.updatedDeposit.sourceType,
          sourceBusinessId: result.updatedDeposit.sourceBusinessId,
          sourceBusiness: result.updatedDeposit.sourceBusiness,
          amount: Number(result.updatedDeposit.amount),
          depositDate: result.updatedDeposit.depositDate.toISOString(),
          autoGeneratedNote: result.updatedDeposit.autoGeneratedNote,
          manualNote: result.updatedDeposit.manualNote,
          transactionType: result.updatedDeposit.transactionType,
          createdBy: result.updatedDeposit.creator,
          createdAt: result.updatedDeposit.createdAt.toISOString(),
        },
        expenseAccountBalance: result.newBalance,
      },
    })
  } catch (error) {
    console.error('Error updating deposit:', error)
    return NextResponse.json(
      {
        error:
          error instanceof Error ? error.message : 'Failed to update deposit',
      },
      { status: 500 }
    )
  }
}
