import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import {
  validateDepositAmount,
  validateDepositEdit,
  updateExpenseAccountBalanceTx,
  isWithinEditWindow,
} from '@/lib/expense-account-utils'
import { getEffectivePermissions, isSystemAdmin } from '@/lib/permission-utils'
import { getServerUser } from '@/lib/get-server-user'

/**
 * GET /api/expense-account/[accountId]/deposits/[depositId]
 * Get single deposit details
 */
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ accountId: string; depositId: string }> }
) {
  try {
    const user = await getServerUser()
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // Get user permissions
    const permissions = getEffectivePermissions(user)
    if (!permissions.canAccessExpenseAccount) {
      return NextResponse.json(
        { error: 'You do not have permission to access expense accounts' },
        { status: 403 }
      )
    }

    const { accountId, depositId } = await params

    // Get deposit with relations
    const deposit = await prisma.expenseAccountDeposits.findUnique({
      where: { id: depositId },
      include: {
        expenseAccount: {
          select: {
            id: true,
            accountNumber: true,
            accountName: true,
          },
        },
        sourceBusiness: {
          select: { id: true, name: true, type: true },
        },
        creator: {
          select: { id: true, name: true, email: true },
        },
      },
    })

    if (!deposit) {
      return NextResponse.json({ error: 'Deposit not found' }, { status: 404 })
    }

    // Verify deposit belongs to the specified account
    if (deposit.expenseAccountId !== accountId) {
      return NextResponse.json(
        { error: 'Deposit does not belong to this expense account' },
        { status: 400 }
      )
    }

    // Parse source account name from auto-generated note for ACCOUNT_TRANSFER deposits
    const autoTransferSource = deposit.sourceType === 'ACCOUNT_TRANSFER'
      ? (deposit.autoGeneratedNote?.match(/"([^"]+)"/)?.[1] ?? null)
      : null

    // Check if a petty cash request is linked to this deposit
    let pettyCashRequest: any = null
    if (deposit.sourceType === 'PETTY_CASH') {
      const pc = await prisma.pettyCashRequests.findFirst({
        where: { depositId: depositId },
        select: {
          id: true, purpose: true, requestedAmount: true, approvedAmount: true,
          spentAmount: true, returnAmount: true, status: true, requestedAt: true, settledAt: true,
          requester: { select: { name: true } },
          approver:  { select: { name: true } },
          transactions: {
            select: {
              id: true, amount: true, description: true, transactionDate: true,
              payeeType: true, payeeSupplierId: true, payeeEmployeeId: true, payeeUserId: true,
              createdBy: true,
              category: { select: { name: true } },
            },
            orderBy: { transactionDate: 'asc' },
          },
        },
      })
      if (pc) {
        // Resolve payee names/phones and creator names via batch queries
        const supplierIds = [...new Set(pc.transactions.filter((t: any) => t.payeeSupplierId).map((t: any) => t.payeeSupplierId as string))]
        const employeeIds = [...new Set(pc.transactions.filter((t: any) => t.payeeEmployeeId).map((t: any) => t.payeeEmployeeId as string))]
        const userIds = [...new Set(pc.transactions.filter((t: any) => t.payeeUserId).map((t: any) => t.payeeUserId as string))]
        const creatorIds = [...new Set(pc.transactions.map((t: any) => t.createdBy as string))]
        const [suppliers, employees, payeeUsers, creators] = await Promise.all([
          supplierIds.length ? prisma.businessSuppliers.findMany({ where: { id: { in: supplierIds } }, select: { id: true, name: true, phone: true, contactPerson: true } }) : [],
          employeeIds.length ? prisma.employees.findMany({ where: { id: { in: employeeIds } }, select: { id: true, firstName: true, lastName: true, phone: true } }) : [],
          userIds.length ? prisma.users.findMany({ where: { id: { in: userIds } }, select: { id: true, name: true } }) : [],
          creatorIds.length ? prisma.users.findMany({ where: { id: { in: creatorIds } }, select: { id: true, name: true } }) : [],
        ])
        const supplierMap = Object.fromEntries((suppliers as any[]).map(s => [s.id, s]))
        const employeeMap = Object.fromEntries((employees as any[]).map(e => [e.id, e]))
        const userMap = Object.fromEntries((payeeUsers as any[]).map(u => [u.id, u.name]))
        const creatorMap = Object.fromEntries((creators as any[]).map(u => [u.id, u.name]))
        const transactions = pc.transactions.map((t: any) => {
          let payeeName = '—', payeePhone: string | null = null, payeeContact: string | null = null
          if (t.payeeSupplierId && supplierMap[t.payeeSupplierId]) {
            const s = supplierMap[t.payeeSupplierId]
            payeeName = s.name; payeePhone = s.phone ?? null; payeeContact = s.contactPerson ?? null
          } else if (t.payeeEmployeeId && employeeMap[t.payeeEmployeeId]) {
            const e = employeeMap[t.payeeEmployeeId]
            payeeName = `${e.firstName} ${e.lastName}`; payeePhone = e.phone ?? null
          } else if (t.payeeUserId && userMap[t.payeeUserId]) {
            payeeName = userMap[t.payeeUserId]
          }
          return {
            id: t.id, amount: Number(t.amount), description: t.description,
            category: t.category?.name ?? null, payeeName, payeePhone, payeeContact,
            paidBy: creatorMap[t.createdBy] ?? '—',
            transactionDate: t.transactionDate,
          }
        })
        pettyCashRequest = {
          id: pc.id,
          purpose: pc.purpose,
          requestedAmount: Number(pc.requestedAmount),
          approvedAmount: pc.approvedAmount ? Number(pc.approvedAmount) : null,
          spentAmount: pc.spentAmount ? Number(pc.spentAmount) : null,
          returnAmount: pc.returnAmount ? Number(pc.returnAmount) : null,
          status: pc.status,
          requestedAt: pc.requestedAt,
          settledAt: pc.settledAt,
          requestedBy: pc.requester?.name ?? '—',
          approvedBy: pc.approver?.name ?? '—',
          transactions,
        }
      }
    }

    return NextResponse.json({
      success: true,
      data: {
        deposit: {
          id: deposit.id,
          expenseAccountId: deposit.expenseAccountId,
          expenseAccount: deposit.expenseAccount,
          sourceType: deposit.sourceType,
          sourceBusinessId: deposit.sourceBusinessId,
          sourceBusiness: deposit.sourceBusiness,
          amount: Number(deposit.amount),
          depositDate: deposit.depositDate.toISOString(),
          autoGeneratedNote: deposit.autoGeneratedNote,
          autoTransferSource,
          manualNote: deposit.manualNote,
          transactionType: deposit.transactionType,
          createdBy: deposit.creator,
          createdAt: deposit.createdAt.toISOString(),
        },
        pettyCashRequest,
      },
    })
  } catch (error) {
    console.error('Error fetching deposit:', error)
    return NextResponse.json(
      { error: 'Failed to fetch deposit' },
      { status: 500 }
    )
  }
}

/**
 * PATCH /api/expense-account/[accountId]/deposits/[depositId]
 * Update deposit details
 */
export async function PATCH(
  request: NextRequest,
  { params }: { params: Promise<{ accountId: string; depositId: string }> }
) {
  try {
    const user = await getServerUser()
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // Get user permissions
    const permissions = getEffectivePermissions(user)
    const isAdmin = isSystemAdmin(user)

    if (!permissions.canEditExpenseTransactions) {
      return NextResponse.json(
        { error: 'You do not have permission to edit expense transactions' },
        { status: 403 }
      )
    }

    const { accountId, depositId } = await params

    // Get existing deposit
    const existingDeposit = await prisma.expenseAccountDeposits.findUnique({
      where: { id: depositId },
      select: {
        id: true,
        amount: true,
        depositDate: true,
        expenseAccountId: true,
        sourceType: true,
        sourceBusinessId: true,
        createdAt: true,
      },
    })

    if (!existingDeposit) {
      return NextResponse.json({ error: 'Deposit not found' }, { status: 404 })
    }

    // Verify deposit belongs to the specified account
    if (existingDeposit.expenseAccountId !== accountId) {
      return NextResponse.json(
        { error: 'Deposit does not belong to this expense account' },
        { status: 400 }
      )
    }

    // Auto-transfer (ACCOUNT_TRANSFER) deposits are system-generated and cannot be edited by anyone
    if (existingDeposit.sourceType === 'ACCOUNT_TRANSFER') {
      return NextResponse.json(
        { error: 'Auto-transfer deposits cannot be edited. They are system-generated records.' },
        { status: 403 }
      )
    }

    // Check if within edit window (5 days for non-admins)
    const editWindowCheck = isWithinEditWindow(existingDeposit.createdAt, isAdmin)
    if (!editWindowCheck.allowed) {
      return NextResponse.json(
        { error: editWindowCheck.error },
        { status: 403 }
      )
    }

    // Parse request body
    const body = await request.json()
    const { amount, depositDate, manualNote, transactionType } = body

    // Build update data
    const updateData: any = {}

    // Validate and update amount if provided
    if (amount !== undefined) {
      const amountValidation = validateDepositAmount(Number(amount))
      if (!amountValidation.valid) {
        return NextResponse.json(
          { error: amountValidation.error },
          { status: 400 }
        )
      }

      // Validate that this change won't cause negative balances
      const editValidation = await validateDepositEdit(
        depositId,
        accountId,
        Number(amount)
      )
      if (!editValidation.valid) {
        return NextResponse.json(
          { error: editValidation.error },
          { status: 400 }
        )
      }

      updateData.amount = Number(amount)
    }

    // Validate and update deposit date if provided
    if (depositDate !== undefined) {
      // Parse as UTC midnight explicitly to avoid server timezone shifts
      const [y, m, d] = String(depositDate).split('-').map(Number)
      const depDate = new Date(Date.UTC(y, m - 1, d))
      const depDateStr = depositDate.split('T')[0]
      const serverToday = new Date().toISOString().split('T')[0]
      if (depDateStr > serverToday) {
        return NextResponse.json(
          { error: 'Deposit date cannot be in the future' },
          { status: 400 }
        )
      }
      updateData.depositDate = depDate
    }

    // Update other fields
    if (manualNote !== undefined) updateData.manualNote = manualNote?.trim() || null
    if (transactionType !== undefined)
      updateData.transactionType = transactionType?.trim() || null

    // Use transaction to update deposit and recalculate balance
    const result = await prisma.$transaction(async (tx) => {
      // Update deposit
      const updatedDeposit = await tx.expenseAccountDeposits.update({
        where: { id: depositId },
        data: updateData,
        include: {
          sourceBusiness: {
            select: { id: true, name: true, type: true },
          },
          creator: {
            select: { id: true, name: true, email: true },
          },
        },
      })

      // Recalculate and update account balance
      const newBalance = await updateExpenseAccountBalanceTx(tx, accountId)

      return { updatedDeposit, newBalance }
    })

    return NextResponse.json({
      success: true,
      message: 'Deposit updated successfully',
      data: {
        deposit: {
          id: result.updatedDeposit.id,
          expenseAccountId: result.updatedDeposit.expenseAccountId,
          sourceType: result.updatedDeposit.sourceType,
          sourceBusinessId: result.updatedDeposit.sourceBusinessId,
          sourceBusiness: result.updatedDeposit.sourceBusiness,
          amount: Number(result.updatedDeposit.amount),
          depositDate: result.updatedDeposit.depositDate.toISOString(),
          autoGeneratedNote: result.updatedDeposit.autoGeneratedNote,
          manualNote: result.updatedDeposit.manualNote,
          transactionType: result.updatedDeposit.transactionType,
          createdBy: result.updatedDeposit.creator,
          createdAt: result.updatedDeposit.createdAt.toISOString(),
        },
        expenseAccountBalance: result.newBalance,
      },
    })
  } catch (error) {
    console.error('Error updating deposit:', error)
    return NextResponse.json(
      {
        error:
          error instanceof Error ? error.message : 'Failed to update deposit',
      },
      { status: 500 }
    )
  }
}
