import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { getServerUser } from '@/lib/get-server-user'
import { getGlobalPayrollAccount } from '@/lib/payroll-account-utils'

interface RouteParams {
  params: Promise<{ periodId: string }>
}

/**
 * POST /api/payroll/periods/[periodId]/zimra/process-levy
 * Debits the AIDS Levy amount from the payroll account (employer cost).
 * Records a negative PayrollAccountDeposit (transactionType = ZIMRA_AIDS_LEVY).
 * Updates PayrollZimraRemittances.status → LEVY_PROCESSED.
 *
 * The Gross PAYE portion is employee-funded and already flows through payslip capture.
 * Only the AIDS Levy (employer cost) is debited here.
 */
export async function POST(request: NextRequest, { params }: RouteParams) {
  try {
    const user = await getServerUser()
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const { periodId } = await params

    // Get existing remittance record
    const remittance = await prisma.payrollZimraRemittances.findUnique({
      where: { payrollPeriodId: periodId },
    })
    if (!remittance) {
      return NextResponse.json(
        { error: 'ZIMRA remittance record not found. Load the ZIMRA summary first.' },
        { status: 404 }
      )
    }
    if (remittance.status !== 'PENDING') {
      return NextResponse.json(
        { error: `Cannot process levy — current status is ${remittance.status}` },
        { status: 400 }
      )
    }

    const levyAmount = Number(remittance.aidsLevy)
    if (levyAmount <= 0) {
      return NextResponse.json(
        { error: 'AIDS Levy amount is zero — nothing to process' },
        { status: 400 }
      )
    }

    // Get payroll account and check balance
    const payrollAccount = await getGlobalPayrollAccount()
    if (!payrollAccount) {
      return NextResponse.json({ error: 'Payroll account not found' }, { status: 404 })
    }
    if (Number(payrollAccount.balance) < levyAmount) {
      return NextResponse.json(
        {
          error: `Insufficient payroll account balance. Balance: $${Number(payrollAccount.balance).toFixed(2)}, required: $${levyAmount.toFixed(2)}`,
        },
        { status: 400 }
      )
    }

    // Get period for businessId
    const period = await prisma.payrollPeriods.findUnique({
      where: { id: periodId },
      select: { businessId: true },
    })
    if (!period) {
      return NextResponse.json({ error: 'Period not found' }, { status: 404 })
    }

    // Execute debit + status update in a transaction
    await prisma.$transaction([
      // Debit payroll account balance
      prisma.payrollAccounts.update({
        where: { id: payrollAccount.id },
        data: { balance: { decrement: levyAmount }, updatedAt: new Date() },
      }),
      // Record the debit as a negative deposit entry (for transaction history)
      prisma.payrollAccountDeposits.create({
        data: {
          payrollAccountId: payrollAccount.id,
          businessId: period.businessId,
          amount: -levyAmount,
          transactionType: 'ZIMRA_AIDS_LEVY',
          autoGeneratedNote: `AIDS Levy ZIMRA payment — payroll period ${periodId}`,
          createdBy: user.id,
        },
      }),
      // Update remittance status
      prisma.payrollZimraRemittances.update({
        where: { id: remittance.id },
        data: {
          status: 'LEVY_PROCESSED',
          levyProcessedAt: new Date(),
          levyProcessedBy: user.id,
          updatedAt: new Date(),
        },
      }),
    ])

    return NextResponse.json({
      success: true,
      message: `AIDS Levy of $${levyAmount.toFixed(2)} debited from payroll account`,
      levyAmount,
    })
  } catch (error) {
    console.error('Error processing ZIMRA AIDS levy:', error)
    return NextResponse.json({ error: 'Failed to process AIDS levy' }, { status: 500 })
  }
}
