import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { getServerUser } from '@/lib/get-server-user'
import { getEffectivePermissions } from '@/lib/permission-utils'

/**
 * POST /api/expense-account/outgoing-loans/[loanId]/payments
 * Record a manual repayment against an outgoing loan
 * Creates a deposit to the account + an AccountOutgoingLoanPayments record
 */
export async function POST(
  request: NextRequest,
  { params }: { params: { loanId: string } }
) {
  try {
    const user = await getServerUser()
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const permissions = getEffectivePermissions(user)
    if (!permissions.canManageLending && user.role !== 'admin') {
      return NextResponse.json({ error: 'Permission denied — canManageLending required' }, { status: 403 })
    }

    const body = await request.json()
    const { amount, paymentDate, paymentMethod = 'CASH', notes } = body

    if (!amount || Number(amount) <= 0) {
      return NextResponse.json({ error: 'Invalid repayment amount' }, { status: 400 })
    }
    if (!paymentDate) {
      return NextResponse.json({ error: 'paymentDate is required' }, { status: 400 })
    }

    const loan = await prisma.accountOutgoingLoans.findUnique({
      where: { id: params.loanId },
      include: {
        recipientPerson: { select: { fullName: true } },
        recipientBusiness: { select: { name: true } },
        recipientEmployee: { select: { fullName: true } },
        payrollAccount: { select: { id: true, businessId: true } },
      },
    })

    if (!loan) return NextResponse.json({ error: 'Loan not found' }, { status: 404 })
    if (loan.status !== 'ACTIVE') {
      return NextResponse.json({ error: `Cannot record repayment for loan in status: ${loan.status}` }, { status: 400 })
    }

    const repayAmount = Number(amount)
    const remaining = Number(loan.remainingBalance)

    if (repayAmount > remaining + 0.001) {
      return NextResponse.json({
        error: `Repayment exceeds outstanding balance of $${remaining.toFixed(2)}`,
      }, { status: 400 })
    }

    const recipientName = loan.recipientPerson?.fullName ?? loan.recipientBusiness?.name ?? loan.recipientEmployee?.fullName ?? 'Unknown'
    const newBalance = Math.max(0, remaining - repayAmount)
    const isFullyPaid = newBalance <= 0.001
    const isPayrollLoan = !!loan.payrollAccountId

    await prisma.$transaction(async (tx: any) => {
      let depositId: string | null = null

      if (isPayrollLoan) {
        // Credit payroll account for repayments on payroll-sourced loans
        const deposit = await tx.payrollAccountDeposits.create({
          data: {
            payrollAccountId: loan.payrollAccountId!,
            businessId: loan.payrollAccount?.businessId ?? loan.payrollAccountId!,
            amount: repayAmount,
            depositDate: new Date(paymentDate),
            transactionType: 'LOAN_REPAYMENT',
            autoGeneratedNote: `📥 Loan repayment from ${recipientName} — ${loan.loanNumber}`,
            createdBy: user.id,
          },
        })
        depositId = deposit.id

        await tx.payrollAccounts.update({
          where: { id: loan.payrollAccountId! },
          data: { balance: { increment: repayAmount }, updatedAt: new Date() },
        })
      } else {
        // Credit expense account for repayments on expense-account-sourced loans
        const deposit = await tx.expenseAccountDeposits.create({
          data: {
            expenseAccountId: loan.expenseAccountId!,
            sourceType: 'LOAN_REPAYMENT',
            amount: repayAmount,
            depositDate: new Date(paymentDate),
            autoGeneratedNote: `📥 Loan repayment from ${recipientName} — ${loan.loanNumber}`,
            manualNote: notes ?? null,
            createdBy: user.id,
          },
        })
        depositId = deposit.id

        await tx.expenseAccounts.update({
          where: { id: loan.expenseAccountId! },
          data: { balance: { increment: repayAmount } },
        })

        // For BUSINESS loans: also debit the borrower's primary expense account
        if (loan.loanType === 'BUSINESS' && loan.recipientBusinessId) {
          const borrowerAccount = await tx.expenseAccounts.findFirst({
            where: { businessId: loan.recipientBusinessId, isActive: true, isSibling: false },
            orderBy: { createdAt: 'asc' },
            select: { id: true },
          })
          if (borrowerAccount) {
            await tx.expenseAccountPayments.create({
              data: {
                expenseAccountId: borrowerAccount.id,
                payeeType: 'NONE',
                amount: repayAmount,
                paymentDate: new Date(paymentDate),
                paymentType: 'LOAN_REPAYMENT',
                notes: notes ?? `💸 Loan repayment — ${loan.loanNumber}`,
                status: 'SUBMITTED',
                createdBy: user.id,
              },
            })
            await tx.expenseAccounts.update({
              where: { id: borrowerAccount.id },
              data: { balance: { decrement: repayAmount } },
            })
          }
        }
      }

      // Create repayment record
      await tx.accountOutgoingLoanPayments.create({
        data: {
          loanId: loan.id,
          amount: repayAmount,
          paymentDate: new Date(paymentDate),
          paymentMethod,
          depositId,
          notes: notes ?? null,
          recordedBy: user.id,
        },
      })

      // Update loan balance
      await tx.accountOutgoingLoans.update({
        where: { id: loan.id },
        data: {
          remainingBalance: newBalance,
          status: isFullyPaid ? 'PAID_OFF' : 'ACTIVE',
        },
      })
    })

    return NextResponse.json({
      success: true,
      data: {
        message: isFullyPaid ? 'Loan fully repaid and marked as Paid Off' : `Repayment recorded. Remaining: $${newBalance.toFixed(2)}`,
        remainingBalance: newBalance,
        status: isFullyPaid ? 'PAID_OFF' : 'ACTIVE',
      },
    })
  } catch (error) {
    console.error('Error recording loan repayment:', error)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
