/**
 * Universal Receipt Builder
 * Creates receipt data for any business type based on order information
 */

import type { ReceiptData } from '@/types/printing'

interface BusinessInfo {
  id: string
  name: string
  type: string
  settings?: {
    address?: string
    phone?: string
    email?: string
    logo?: string
    taxId?: string
    receiptFooter?: string
    returnPolicy?: string
  }
}

interface OrderData {
  id: string
  orderNumber: string
  orderDate: string | Date
  orderType: string
  status: string
  subtotal: number
  taxAmount: number
  discountAmount?: number
  totalAmount: number
  paymentMethod?: string
  paymentStatus: string
  customerName?: string
  customerInfo?: any
  employeeName?: string
  employeeId?: string
  notes?: string
  wifiTokens?: Array<{
    itemName: string
    tokenCode: string
    packageName: string
    duration: number
    bandwidthDownMb: number
    bandwidthUpMb: number
    ssid?: string
    portalUrl?: string
    instructions?: string
    success: boolean
  }>
  items: Array<{
    name: string
    quantity: number
    unitPrice: number
    totalPrice: number
    productVariant?: {
      product?: {
        name: string
      }
    }
  }>
  attributes?: any
}

interface ReceiptBuilderOptions {
  showLogo?: boolean
  showReturnPolicy?: boolean
  customFooter?: string
}

/**
 * Business type specific configurations
 */
const BUSINESS_CONFIGS = {
  grocery: {
    defaultAddress: '123 Main Street, City, State 12345',
    defaultPhone: '(555) 123-4567',
    showLoyaltyInfo: true,
    showSnapEligible: true,
    footerMessage: 'Thank you for shopping with us!'
  },
  restaurant: {
    defaultAddress: '456 Food Avenue, City, State 12345',
    defaultPhone: '(555) 234-5678',
    showTableNumber: true,
    showServerInfo: true,
    footerMessage: 'Thank you for dining with us!'
  },
  hardware: {
    defaultAddress: '789 Tool Street, City, State 12345',
    defaultPhone: '(555) 345-6789',
    showProjectReference: true,
    footerMessage: 'Thank you for your business!'
  },
  clothing: {
    defaultAddress: '321 Fashion Blvd, City, State 12345',
    defaultPhone: '(555) 456-7890',
    showSizeColor: true,
    returnPolicy: 'Returns accepted within 30 days with receipt',
    footerMessage: 'Thank you for shopping with us!'
  },
  default: {
    defaultAddress: '123 Business Street, City, State 12345',
    defaultPhone: '(555) 000-0000',
    footerMessage: 'Thank you for your business!'
  }
}

/**
 * Get business-specific configuration
 */
function getBusinessConfig(businessType: string) {
  return BUSINESS_CONFIGS[businessType as keyof typeof BUSINESS_CONFIGS] || BUSINESS_CONFIGS.default
}

/**
 * Build receipt data from order and business information
 */
export function buildReceiptData(
  order: OrderData,
  business: BusinessInfo,
  options: ReceiptBuilderOptions = {}
): ReceiptData {
  const config = getBusinessConfig(business.type)
  const settings = business.settings || {}

  // Build receipt data using the correct ReceiptData interface
  const receiptData: ReceiptData = {
    receiptNumber: {
      globalId: `receipt_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
      dailySequence: '001', // This would be generated by the receipt numbering service
      formattedNumber: `RCP-${new Date().toISOString().split('T')[0]}-001`
    },
    businessId: business.id,
    businessType: business.type as any, // Cast to BusinessType
    businessName: (business.name && business.name.trim()) || 'Business',
    businessAddress: settings.address || config.defaultAddress,
    businessPhone: settings.phone || config.defaultPhone,
    businessEmail: settings.email,
    transactionId: order.id || `txn_${Date.now()}`,
    transactionDate: order.orderDate ? new Date(order.orderDate) : new Date(),
    salespersonName: order.employeeName || 'Unknown',
    salespersonId: order.employeeId || 'unknown',
    items: order.items.map(item => ({
      name: item.name,
      sku: undefined, // SKU not available in current order structure
      quantity: item.quantity,
      unitPrice: item.unitPrice,
      totalPrice: item.totalPrice,
      notes: undefined
    })),
    subtotal: order.subtotal,
    tax: order.taxAmount,
    discount: order.discountAmount,
    total: order.totalAmount,
    paymentMethod: order.paymentMethod || 'cash',
    amountPaid: order.paymentStatus === 'PAID' ? order.totalAmount : undefined,
    changeDue: undefined,
    wifiTokens: order.wifiTokens?.filter(token => token.success).map(token => ({
      token: token.tokenCode,
      durationMinutes: token.duration,
      bandwidthDownMb: token.bandwidthDownMb,
      bandwidthUpMb: token.bandwidthUpMb,
      ssid: token.ssid,
      portalUrl: token.portalUrl,
      instructions: token.instructions
    })),
    businessSpecificData: buildBusinessSpecificData(order, business.type),
    footerMessage: settings.receiptFooter || config.footerMessage,
    returnPolicy: settings.returnPolicy
  }

  return receiptData
}

/**
 * Build business-specific data based on business type
 */
function buildBusinessSpecificData(order: OrderData, businessType: string): any {
  switch (businessType) {
    case 'grocery':
      return {
        items: order.items.map(item => ({
          weight: undefined,
          unitPricing: undefined,
          expirationDate: undefined,
          category: undefined
        }))
      };
    case 'restaurant':
      return {
        receiptType: 'customer',
        tableNumber: order.attributes?.tableNumber,
        serverName: order.attributes?.serverName,
        orderTime: order.orderDate ? new Date(order.orderDate) : new Date(),
        items: order.items.map(() => ({
          allergens: undefined,
          dietaryRestrictions: undefined,
          spiceLevel: undefined,
          preparationTime: undefined,
          calories: undefined,
          specialInstructions: undefined
        }))
      };
    case 'clothing':
      return {
        items: order.items.map(() => ({
          size: undefined,
          color: undefined,
          season: undefined,
          brand: undefined
        })),
        returnPolicy: 'Returns accepted within 30 days with receipt',
        returnWindowDays: 30
      };
    case 'hardware':
      return {
        items: order.items.map(() => ({
          cutToSizeDimensions: undefined,
          bulkQuantity: undefined,
          bulkPricePerUnit: undefined,
          specialOrderETA: undefined,
          manufacturer: undefined
        })),
        projectReference: order.attributes?.projectReference
      };
    default:
      return undefined;
  }
}

/**
 * Fetch business information from API
 */
export async function fetchBusinessInfo(businessId: string): Promise<BusinessInfo | null> {
  try {
    const response = await fetch(`/api/businesses/${businessId}`)
    if (!response.ok) {
      console.error('Failed to fetch business info:', response.statusText)
      return null
    }

    const data = await response.json()
    if (data.success) {
      return {
        id: data.data.id,
        name: data.data.name,
        type: data.data.type,
        settings: data.data.settings
      }
    }

    return null
  } catch (error) {
    console.error('Error fetching business info:', error)
    return null
  }
}

/**
 * Build receipt data from order (convenience function that fetches business info)
 */
export async function buildReceiptFromOrder(
  order: OrderData,
  businessId: string,
  options: ReceiptBuilderOptions = {}
): Promise<ReceiptData | null> {
  const businessInfo = await fetchBusinessInfo(businessId)

  if (!businessInfo) {
    console.error('Could not fetch business information for receipt')
    return null
  }

  return buildReceiptData(order, businessInfo, options)
}

/**
 * Build receipt data with provided business info (for when you already have it)
 */
export function buildReceiptWithBusinessInfo(
  order: OrderData,
  business: BusinessInfo,
  options: ReceiptBuilderOptions = {}
): ReceiptData {
  return buildReceiptData(order, business, options)
}
