import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { getServerUser } from '@/lib/get-server-user'
import { getEffectivePermissions } from '@/lib/permission-utils'
import { getGlobalPayrollAccount } from '@/lib/payroll-account-utils'

/**
 * POST /api/payroll/account/fund
 * Fund payroll account from business cash boxes.
 *
 * Body:
 * - transfers: Array<{ businessId: string, amount: number }>
 */
export async function POST(request: NextRequest) {
  try {
    const user = await getServerUser()
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const permissions = getEffectivePermissions(user)
    if (!permissions.canMakeExpensePayments && user.role !== 'admin') {
      return NextResponse.json({ error: 'Permission denied' }, { status: 403 })
    }

    const body = await request.json()
    const { transfers } = body

    if (!Array.isArray(transfers) || transfers.length === 0) {
      return NextResponse.json({ error: 'transfers array is required' }, { status: 400 })
    }

    const validTransfers = transfers.filter(
      (t: any) => t.businessId && Number(t.amount) > 0
    )
    if (validTransfers.length === 0) {
      return NextResponse.json({ error: 'No valid transfers with amount > 0' }, { status: 400 })
    }

    // Get payroll account
    const payrollAccount = await getGlobalPayrollAccount()
    if (!payrollAccount) {
      return NextResponse.json({ error: 'Payroll account not found' }, { status: 404 })
    }

    // Validate each business has sufficient cashbox balance
    const businessIds = validTransfers.map((t: any) => t.businessId)
    const bucketTotals = await prisma.cashBucketEntry.groupBy({
      by: ['businessId', 'direction'],
      where: { businessId: { in: businessIds } },
      _sum: { amount: true },
    })

    const businesses = await prisma.businesses.findMany({
      where: { id: { in: businessIds } },
      select: { id: true, name: true },
    })

    for (const t of validTransfers) {
      const biz = businesses.find((b) => b.id === t.businessId)
      if (!biz) {
        return NextResponse.json({ error: `Business ${t.businessId} not found` }, { status: 404 })
      }
      const inflow = Number(bucketTotals.find((r) => r.businessId === t.businessId && r.direction === 'INFLOW')?._sum.amount ?? 0)
      const outflow = Number(bucketTotals.find((r) => r.businessId === t.businessId && r.direction === 'OUTFLOW')?._sum.amount ?? 0)
      const balance = inflow - outflow
      if (balance < Number(t.amount)) {
        return NextResponse.json({
          error: `Insufficient cash box balance for ${biz.name}. Available: $${balance.toFixed(2)}, Requested: $${Number(t.amount).toFixed(2)}`,
        }, { status: 400 })
      }
    }

    const totalTransferred = validTransfers.reduce((s: number, t: any) => s + Number(t.amount), 0)
    const now = new Date()

    await prisma.$transaction(async (tx: any) => {
      for (const transfer of validTransfers) {
        const biz = businesses.find((b) => b.id === transfer.businessId)!
        const amount = Number(transfer.amount)

        // Debit cashbox — OUTFLOW entry
        await tx.cashBucketEntry.create({
          data: {
            businessId: transfer.businessId,
            entryType: 'PAYROLL_FUNDING',
            direction: 'OUTFLOW',
            amount,
            referenceType: 'PAYROLL_ACCOUNT',
            referenceId: payrollAccount.id,
            notes: `💵 Payroll funding — $${amount.toFixed(2)}`,
            entryDate: now,
            createdBy: user.id,
          },
        })

        // Credit payroll account — deposit record
        await tx.payrollAccountDeposits.create({
          data: {
            payrollAccountId: payrollAccount.id,
            businessId: transfer.businessId,
            amount,
            transactionType: 'PAYROLL_FUNDING',
            autoGeneratedNote: `Funded from ${biz.name} cash box`,
            createdBy: user.id,
          },
        })
      }

      // Credit payroll account balance
      await tx.payrollAccounts.update({
        where: { id: payrollAccount.id },
        data: { balance: { increment: totalTransferred }, updatedAt: now },
      })
    })

    return NextResponse.json({
      success: true,
      message: `$${totalTransferred.toFixed(2)} transferred to payroll account from ${validTransfers.length} cash box(es)`,
      data: { totalTransferred, transferCount: validTransfers.length },
    }, { status: 201 })
  } catch (error) {
    console.error('Error batch funding payroll account:', error)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
