import { NextRequest, NextResponse } from 'next/server'
import { Prisma } from '@prisma/client'
import { prisma } from '@/lib/prisma'
import { getServerUser } from '@/lib/get-server-user'
import { getEffectivePermissions } from '@/lib/permission-utils'

type Params = { params: Promise<{ businessId: string; reportId: string }> }

/**
 * Ensures the EOD_RENT_TRANSFER deposit exists for the given report date.
 * If it doesn't exist yet, creates it now (same atomic logic as the eod-transfer route).
 * Idempotent: does nothing if deposit already exists.
 */
/**
 * Ensures the EOD_RENT_TRANSFER deposit exists and returns the deposit + account info
 * so the caller can upsert a cash allocation line item for it.
 */
async function ensureRentTransfer(
  businessId: string,
  reportDate: Date,
  userId: string,
): Promise<{ depositId: string; expenseAccountId: string; accountName: string; amount: number } | null> {
  const config = await prisma.businessRentConfig.findUnique({
    where: { businessId },
    include: {
      expenseAccount: { select: { id: true, accountName: true, balance: true } },
    },
  })
  if (!config || !config.isActive) return null

  const dayStart = new Date(Date.UTC(reportDate.getUTCFullYear(), reportDate.getUTCMonth(), reportDate.getUTCDate(), 0, 0, 0))
  const dayEnd   = new Date(Date.UTC(reportDate.getUTCFullYear(), reportDate.getUTCMonth(), reportDate.getUTCDate(), 23, 59, 59, 999))

  // Return existing deposit if already done
  const existing = await prisma.expenseAccountDeposits.findFirst({
    where: {
      expenseAccountId: config.expenseAccountId,
      sourceType: 'EOD_RENT_TRANSFER',
      depositDate: { gte: dayStart, lte: dayEnd },
    },
  })
  if (existing) {
    return {
      depositId: existing.id,
      expenseAccountId: config.expenseAccountId,
      accountName: config.expenseAccount.accountName,
      amount: Number(existing.amount),
    }
  }

  const transferAmount = Math.ceil(Number(config.dailyTransferAmount))
  if (transferAmount <= 0) return null

  let depositId: string | null = null

  await prisma.$transaction(async (tx: Prisma.TransactionClient) => {
    const bizAcct = await tx.businessAccounts.findUnique({
      where: { businessId },
      select: { balance: true },
    })
    const currentBalance = Number(bizAcct?.balance ?? 0)
    if (currentBalance < transferAmount) return // insufficient funds — skip

    const deposit = await tx.expenseAccountDeposits.create({
      data: {
        expenseAccountId: config.expenseAccountId,
        sourceType: 'EOD_RENT_TRANSFER',
        sourceBusinessId: businessId,
        amount: transferAmount,
        depositDate: dayStart,
        autoGeneratedNote: `Rent transfer confirmed at cash allocation lock`,
        createdBy: userId,
      },
      select: { id: true },
    })
    depositId = deposit.id

    await tx.expenseAccounts.update({
      where: { id: config.expenseAccountId },
      data: { balance: { increment: transferAmount }, updatedAt: new Date() },
    })
    await tx.businessAccounts.update({
      where: { businessId },
      data: { balance: { decrement: transferAmount } },
    })
    await tx.businessTransactions.create({
      data: {
        businessId,
        type: 'DEBIT',
        amount: -transferAmount,
        description: `EOD rent transfer → ${config.expenseAccount.accountName}`,
        balanceAfter: currentBalance - transferAmount,
        createdBy: userId,
        referenceType: 'RENT_TRANSFER',
        referenceId: config.expenseAccountId,
      },
    })
  })

  if (!depositId) return null
  return {
    depositId,
    expenseAccountId: config.expenseAccountId,
    accountName: config.expenseAccount.accountName,
    amount: transferAmount,
  }
}

/**
 * POST /api/cash-allocation/[businessId]/[reportId]/lock
 *
 * Locks the report. Pre-conditions:
 * - All line items must be checked (isChecked = true)
 * - All line items must have actualAmount set and matching reportedAmount exactly
 */
export async function POST(request: NextRequest, { params }: Params) {
  try {
    const user = await getServerUser()
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const { businessId, reportId } = await params
    const permissions = getEffectivePermissions(user, businessId)

    if (user.role !== 'admin' && !permissions.canRunCashAllocationReport) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
    }

    const report = await prisma.cashAllocationReport.findUnique({
      where: { id: reportId },
      include: { lineItems: true },
    })

    if (!report) {
      return NextResponse.json({ error: 'Report not found' }, { status: 404 })
    }
    if (report.businessId !== businessId) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
    }
    if (report.status === 'LOCKED') {
      return NextResponse.json({ error: 'Report is already locked' }, { status: 409 })
    }
    if (report.lineItems.length === 0) {
      return NextResponse.json({ error: 'Cannot lock an empty report' }, { status: 400 })
    }

    // Validate all items are checked with matching amounts
    const mismatches: string[] = []
    for (const item of report.lineItems) {
      if (!item.isChecked) {
        mismatches.push(`"${item.accountName}" is not checked`)
        continue
      }
      if (item.actualAmount === null) {
        mismatches.push(`"${item.accountName}" has no actual amount entered`)
        continue
      }
      const reported = Number(item.reportedAmount)
      const actual = Number(item.actualAmount)
      if (Math.abs(reported - actual) > 0.009) {
        mismatches.push(`"${item.accountName}": reported $${reported.toFixed(2)} ≠ actual $${actual.toFixed(2)}`)
      }
    }

    if (mismatches.length > 0) {
      return NextResponse.json({
        error: 'Cannot lock: validation failed',
        mismatches,
      }, { status: 422 })
    }

    const lockedReport = await prisma.cashAllocationReport.update({
      where: { id: reportId },
      data: { status: 'LOCKED', lockedAt: new Date(), lockedBy: user.id },
      include: { lineItems: { orderBy: [{ sortOrder: 'asc' }, { id: 'asc' }] } },
    })

    // Ensure rent transfer deposit exists and upsert its line item into the report
    try {
      const rent = await ensureRentTransfer(businessId, report.reportDate, user.id)
      if (rent) {
        const alreadyHasRentItem = lockedReport.lineItems.some(
          li => li.sourceType === 'EOD_RENT_TRANSFER'
        )
        if (!alreadyHasRentItem) {
          await prisma.cashAllocationLineItem.create({
            data: {
              reportId,
              expenseAccountId: rent.expenseAccountId,
              accountName: rent.accountName,
              sourceType: 'EOD_RENT_TRANSFER',
              depositId: rent.depositId,
              reportedAmount: rent.amount,
              isChecked: true,
              actualAmount: rent.amount,
              sortOrder: -1, // always first
            },
          })
        }
      }
    } catch (rentErr) {
      console.error('[cash-allocation/lock] Rent transfer/line-item failed (non-fatal):', rentErr)
    }

    // Re-fetch line items so response includes the rent line item
    const finalLineItems = await prisma.cashAllocationLineItem.findMany({
      where: { reportId },
      orderBy: [{ sortOrder: 'asc' }, { id: 'asc' }],
    })

    return NextResponse.json({
      report: { ...lockedReport, lockerName: user.name },
      lineItems: finalLineItems,
    })
  } catch (err) {
    console.error('[POST /api/cash-allocation/lock]', err)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
