-- CreateTable: Payroll Account Deposits
-- This migration adds the payroll account deposits table
-- Idempotent: Works for both fresh installs and upgrades

-- Create payroll_account_deposits table
CREATE TABLE IF NOT EXISTS "payroll_account_deposits" (
    "id" TEXT NOT NULL,
    "payrollAccountId" TEXT NOT NULL,
    "businessId" TEXT NOT NULL,
    "amount" DECIMAL(12,2) NOT NULL,
    "depositDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "transactionType" TEXT NOT NULL,
    "autoGeneratedNote" TEXT,
    "createdBy" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "payroll_account_deposits_pkey" PRIMARY KEY ("id")
);

-- Create indexes for payroll_account_deposits
CREATE INDEX IF NOT EXISTS "payroll_account_deposits_payrollAccountId_idx" ON "payroll_account_deposits"("payrollAccountId");
CREATE INDEX IF NOT EXISTS "payroll_account_deposits_businessId_idx" ON "payroll_account_deposits"("businessId");
CREATE INDEX IF NOT EXISTS "payroll_account_deposits_depositDate_idx" ON "payroll_account_deposits"("depositDate");

-- Add foreign key constraints (only if they don't exist)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'payroll_account_deposits_payrollAccountId_fkey') THEN
        ALTER TABLE "payroll_account_deposits" ADD CONSTRAINT "payroll_account_deposits_payrollAccountId_fkey" FOREIGN KEY ("payrollAccountId") REFERENCES "payroll_accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'payroll_account_deposits_businessId_fkey') THEN
        ALTER TABLE "payroll_account_deposits" ADD CONSTRAINT "payroll_account_deposits_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'payroll_account_deposits_createdBy_fkey') THEN
        ALTER TABLE "payroll_account_deposits" ADD CONSTRAINT "payroll_account_deposits_createdBy_fkey" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
    END IF;
END$$;

-- CreateTable: Payroll Account Payments
-- This migration adds the payroll account payments table
-- Idempotent: Works for both fresh installs and upgrades

-- Create payroll_account_payments table
CREATE TABLE IF NOT EXISTS "payroll_account_payments" (
    "id" TEXT NOT NULL,
    "payrollAccountId" TEXT NOT NULL,
    "employeeId" TEXT NOT NULL,
    "amount" DECIMAL(12,2) NOT NULL,
    "paymentDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "paymentType" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "isAdvance" BOOLEAN NOT NULL DEFAULT false,
    "isLocked" BOOLEAN NOT NULL DEFAULT false,
    "createdBy" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "payroll_account_payments_pkey" PRIMARY KEY ("id")
);

-- Create indexes for payroll_account_payments
CREATE INDEX IF NOT EXISTS "payroll_account_payments_payrollAccountId_idx" ON "payroll_account_payments"("payrollAccountId");
CREATE INDEX IF NOT EXISTS "payroll_account_payments_employeeId_idx" ON "payroll_account_payments"("employeeId");
CREATE INDEX IF NOT EXISTS "payroll_account_payments_paymentDate_idx" ON "payroll_account_payments"("paymentDate");
CREATE INDEX IF NOT EXISTS "payroll_account_payments_status_idx" ON "payroll_account_payments"("status");

-- Add foreign key constraints (only if they don't exist)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'payroll_account_payments_payrollAccountId_fkey') THEN
        ALTER TABLE "payroll_account_payments" ADD CONSTRAINT "payroll_account_payments_payrollAccountId_fkey" FOREIGN KEY ("payrollAccountId") REFERENCES "payroll_accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'payroll_account_payments_employeeId_fkey') THEN
        ALTER TABLE "payroll_account_payments" ADD CONSTRAINT "payroll_account_payments_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "employees"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'payroll_account_payments_createdBy_fkey') THEN
        ALTER TABLE "payroll_account_payments" ADD CONSTRAINT "payroll_account_payments_createdBy_fkey" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
    END IF;
END$$;