import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { getServerUser } from '@/lib/get-server-user'
import { isSystemAdmin, hasPermission } from '@/lib/permission-utils'

/**
 * GET /api/dashboard/cash-box-history?accountId=...
 *   Returns CashAllocationLineItem credits + ExpenseAccountPayments debits for an expense account.
 *
 * GET /api/dashboard/cash-box-history?type=payroll&businessId=...
 *   Returns PayrollAccountDeposits credits + PayrollAccountPayments debits for a business's payroll account.
 *
 * Auth: canAccessFinancialData (expense accounts) or canAccessPayroll (payroll).
 */
export async function GET(request: NextRequest) {
  try {
    const user = await getServerUser()
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const { searchParams } = new URL(request.url)
    const type = searchParams.get('type')

    // ── Payroll branch ──────────────────────────────────────────────────────
    if (type === 'payroll') {
      const businessId = searchParams.get('businessId')
      if (!businessId) {
        return NextResponse.json({ error: 'businessId is required for payroll' }, { status: 400 })
      }

      // Permission check
      if (!isSystemAdmin(user) && !hasPermission(user, 'canAccessPayroll', businessId)) {
        return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
      }

      // Credits: query deposits by businessId directly (same as the dashboard)
      // This works even when the PayrollAccounts record has no businessId set.
      const depositRows = await prisma.payrollAccountDeposits.findMany({
        where: {
          businessId,
          transactionType: 'EOD_AUTO_CONTRIBUTION',
        },
        select: {
          id: true,
          amount: true,
          depositDate: true,
          transactionType: true,
          autoGeneratedNote: true,
          payrollAccountId: true,
          users: { select: { name: true } },
        },
        orderBy: { depositDate: 'desc' },
        take: 100,
      })

      const setAsides = depositRows.map(d => ({
        id: d.id,
        amount: Number(d.amount),
        date: d.depositDate.toISOString(),
        sourceType: d.transactionType,
        notes: d.autoGeneratedNote ?? null,
        createdBy: d.users?.name ?? null,
      }))

      // Derive payroll account IDs from the deposits
      const payrollAccountIds = [...new Set(depositRows.map(d => d.payrollAccountId))]

      // Debits: salary / advance payments from those payroll accounts
      const paymentRows = await prisma.payrollAccountPayments.findMany({
        where: { payrollAccountId: { in: payrollAccountIds } },
        select: {
          id: true,
          amount: true,
          netAmount: true,
          paymentDate: true,
          paymentType: true,
          status: true,
          notes: true,
          isAdvance: true,
          employees: { select: { fullName: true } },
          users_created: { select: { name: true } },
        },
        orderBy: { paymentDate: 'desc' },
        take: 100,
      })

      const payments = paymentRows.map(p => ({
        id: p.id,
        amount: Number(p.netAmount ?? p.amount),
        date: p.paymentDate.toISOString(),
        status: p.status,
        paymentType: p.isAdvance ? 'ADVANCE' : p.paymentType,
        payee: p.employees?.fullName ?? null,
        category: null,
        notes: p.notes,
        receiptNumber: null,
        createdBy: p.users_created?.name ?? null,
      }))

      return NextResponse.json({
        success: true,
        data: {
          accountName: 'Payroll',
          setAsides,
          payments,
          totals: {
            setAside: setAsides.reduce((s, r) => s + r.amount, 0),
            paid: payments.reduce((s, r) => s + r.amount, 0),
          },
        },
      })
    }

    // ── Expense account branch ──────────────────────────────────────────────
    const accountId = searchParams.get('accountId')
    if (!accountId) {
      return NextResponse.json({ error: 'accountId is required' }, { status: 400 })
    }

    // Resolve the account's business for permission check
    const account = await prisma.expenseAccounts.findUnique({
      where: { id: accountId },
      select: { id: true, accountName: true, businessId: true },
    })
    if (!account) {
      return NextResponse.json({ error: 'Account not found' }, { status: 404 })
    }

    // Permission check
    // Account.businessId may be null for virtual/cross-business accounts.
    // Fall back to checking auto-deposit configs to find which business(es) use this account.
    if (!isSystemAdmin(user)) {
      let authorized = false
      if (account.businessId) {
        authorized = hasPermission(user, 'canAccessFinancialData', account.businessId)
      } else {
        // Virtual account — check if user has access to any business that has an auto-deposit config for it
        const autoDepositConfigs = await prisma.expenseAccountAutoDeposit.findMany({
          where: { expenseAccountId: accountId },
          select: { businessId: true },
        })
        authorized = autoDepositConfigs.some(c => hasPermission(user, 'canAccessFinancialData', c.businessId))
      }
      if (!authorized) {
        return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
      }
    }

    // --- Credits: CashAllocationLineItem rows for this account (LOCKED reports only) ---
    const lineItems = await prisma.cashAllocationLineItem.findMany({
      where: {
        expenseAccountId: accountId,
        actualAmount: { not: null },
        report: { status: 'LOCKED' },
      },
      select: {
        id: true,
        actualAmount: true,
        reportedAmount: true,
        sourceType: true,
        report: {
          select: {
            id: true,
            reportDate: true,
            lockedAt: true,
            locker: { select: { name: true } },
            business: { select: { name: true } },
            isGrouped: true,
            groupedRun: { select: { runDate: true, dates: { select: { date: true } } } },
          },
        },
      },
      orderBy: { report: { lockedAt: 'desc' } },
      take: 100,
    })

    const setAsides = lineItems.map(li => ({
      id: li.id,
      amount: Number(li.actualAmount),
      reportedAmount: Number(li.reportedAmount),
      sourceType: li.sourceType,
      reportId: li.report.id,
      date: li.report.isGrouped
        ? (li.report.groupedRun?.runDate ?? li.report.lockedAt?.toISOString() ?? null)
        : (li.report.reportDate?.toISOString() ?? li.report.lockedAt?.toISOString() ?? null),
      lockedAt: li.report.lockedAt?.toISOString() ?? null,
      lockedBy: li.report.locker?.name ?? null,
      businessName: li.report.business?.name ?? null,
      isGrouped: li.report.isGrouped,
    }))

    // --- Debits: ExpenseAccountPayments for this account ---
    const payments = await prisma.expenseAccountPayments.findMany({
      where: {
        expenseAccountId: accountId,
        cancelledAt: null,
        reversedAt: null,
        status: { in: ['SUBMITTED', 'PAID', 'APPROVED'] },
      },
      select: {
        id: true,
        amount: true,
        paymentDate: true,
        paidAt: true,
        status: true,
        paymentType: true,
        notes: true,
        receiptNumber: true,
        payeeType: true,
        payeeUser: { select: { name: true } },
        payeeEmployee: { select: { fullName: true } },
        payeePerson: { select: { fullName: true } },
        payeeBusiness: { select: { name: true } },
        payeeSupplier: { select: { name: true } },
        category: { select: { name: true, emoji: true } },
        creator: { select: { name: true } },
      },
      orderBy: { paymentDate: 'desc' },
      take: 100,
    })

    const payeeLabel = (p: (typeof payments)[number]) => {
      if (p.payeeUser) return p.payeeUser.name
      if (p.payeeEmployee) return p.payeeEmployee.fullName
      if (p.payeePerson) return p.payeePerson.fullName
      if (p.payeeBusiness) return p.payeeBusiness.name
      if (p.payeeSupplier) return p.payeeSupplier.name
      return p.payeeType
    }

    const paymentRows = payments.map(p => ({
      id: p.id,
      amount: Number(p.amount),
      date: (p.paidAt ?? p.paymentDate).toISOString(),
      status: p.status,
      paymentType: p.paymentType,
      payee: payeeLabel(p),
      category: p.category ? `${p.category.emoji ?? ''} ${p.category.name}`.trim() : null,
      notes: p.notes,
      receiptNumber: p.receiptNumber,
      createdBy: p.creator?.name ?? null,
    }))

    return NextResponse.json({
      success: true,
      data: {
        accountName: account.accountName,
        setAsides,
        payments: paymentRows,
        totals: {
          setAside: setAsides.reduce((s, r) => s + r.amount, 0),
          paid: paymentRows.reduce((s, r) => s + r.amount, 0),
        },
      },
    })
  } catch (err) {
    console.error('[GET /api/dashboard/cash-box-history]', err)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
