import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { getServerUser } from '@/lib/get-server-user'
import { getEffectivePermissions } from '@/lib/permission-utils'
import { getGlobalPayrollAccount } from '@/lib/payroll-account-utils'

/**
 * POST /api/expense-account/[accountId]/fund-payroll
 * Transfer funds from this expense account to the global payroll account
 *
 * Body:
 * - amount: number (required)
 * - notes: string (optional)
 */
export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ accountId: string }> }
) {
  try {
    const user = await getServerUser()
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const permissions = getEffectivePermissions(user)
    if (!permissions.canMakeExpensePayments && user.role !== 'admin') {
      return NextResponse.json({ error: 'Permission denied' }, { status: 403 })
    }

    const { accountId } = await params
    const body = await request.json()
    const { amount, notes } = body

    if (!amount || Number(amount) <= 0) {
      return NextResponse.json({ error: 'Amount must be greater than 0' }, { status: 400 })
    }

    // Get expense account
    const account = await prisma.expenseAccounts.findUnique({
      where: { id: accountId },
      select: { id: true, accountName: true, balance: true, isActive: true, businessId: true },
    })
    if (!account) return NextResponse.json({ error: 'Expense account not found' }, { status: 404 })
    if (!account.isActive) return NextResponse.json({ error: 'Expense account is inactive' }, { status: 400 })
    if (!account.businessId) {
      return NextResponse.json({ error: 'Expense account has no associated business' }, { status: 400 })
    }

    const transferAmount = Number(amount)
    if (Number(account.balance) < transferAmount) {
      return NextResponse.json({
        error: `Insufficient balance. Available: $${Number(account.balance).toFixed(2)}`,
      }, { status: 400 })
    }

    // Get global payroll account
    const payrollAccount = await getGlobalPayrollAccount()
    if (!payrollAccount) {
      return NextResponse.json({ error: 'Payroll account not found' }, { status: 404 })
    }

    // Find or create "Payroll Funding" expense category
    let payrollFundingCategory = await prisma.expenseCategories.findFirst({
      where: { name: 'Payroll Funding', isDefault: true },
    })
    if (!payrollFundingCategory) {
      payrollFundingCategory = await prisma.expenseCategories.create({
        data: {
          name: 'Payroll Funding',
          emoji: '💵',
          isDefault: true,
          isUserCreated: false,
          description: 'Transfer from expense account to payroll account',
        },
      })
    }

    const result = await prisma.$transaction(async (tx: any) => {
      // 1. Create expense account payment (debit expense account)
      const payment = await tx.expenseAccountPayments.create({
        data: {
          expenseAccountId: accountId,
          payeeType: 'PAYROLL',
          amount: transferAmount,
          paymentDate: new Date(),
          notes: notes?.trim() || `💵 Payroll funding transfer — $${transferAmount.toFixed(2)}`,
          isFullPayment: false,
          status: 'SUBMITTED',
          paymentType: 'PAYROLL_FUNDING',
          categoryId: payrollFundingCategory!.id,
          createdBy: user.id,
        },
      })

      // 2. Debit expense account balance
      await tx.expenseAccounts.update({
        where: { id: accountId },
        data: { balance: { decrement: transferAmount }, updatedAt: new Date() },
      })

      // 3. Create payroll account deposit (credit payroll account)
      const deposit = await tx.payrollAccountDeposits.create({
        data: {
          payrollAccountId: payrollAccount.id,
          businessId: account.businessId!,
          amount: transferAmount,
          transactionType: 'PAYROLL_FUNDING',
          autoGeneratedNote: `Funded from expense account: ${account.accountName}`,
          createdBy: user.id,
          expenseId: payment.id,
        },
      })

      // 4. Credit payroll account balance
      await tx.payrollAccounts.update({
        where: { id: payrollAccount.id },
        data: { balance: { increment: transferAmount }, updatedAt: new Date() },
      })

      return { payment, deposit }
    })

    return NextResponse.json({
      success: true,
      message: `$${transferAmount.toFixed(2)} transferred to payroll account`,
      data: {
        paymentId: result.payment.id,
        depositId: result.deposit.id,
        amount: transferAmount,
        newExpenseAccountBalance: Number(account.balance) - transferAmount,
      },
    }, { status: 201 })
  } catch (error) {
    console.error('Error funding payroll from expense account:', error)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
