import { NextRequest, NextResponse } from 'next/server'
import { Prisma } from '@prisma/client'
import { prisma } from '@/lib/prisma'
import { getServerUser } from '@/lib/get-server-user'
import { getEffectivePermissions } from '@/lib/permission-utils'
import { getAvailableCashForAllocation, PAYROLL_ALLOCATION_CONFIG_KEY } from '@/lib/eod-utils'

type Params = { params: Promise<{ businessId: string }> }

/**
 * POST /api/business/[businessId]/allocation-backlog/catch-up
 * Body: { allocationType: 'RENT' | 'AUTO_DEPOSIT' | 'PAYROLL', configKey: string, amount?: number }
 *
 * Manually transfers cash toward a backlog of skipped EOD allocations (rent, an
 * expense/loan auto-deposit, or payroll) now that funds may be available, without
 * waiting for the regular daily EOD cycle. Applies to the oldest outstanding skip
 * days first; `amount` optionally caps how much to catch up (defaults to the full
 * outstanding backlog). Always re-checked against real available cash — this never
 * creates a deposit the cash bucket can't actually back.
 */
export async function POST(request: NextRequest, { params }: Params) {
  try {
    const user = await getServerUser()
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const { businessId } = await params
    const permissions = getEffectivePermissions(user, businessId)
    const canCatchUp = user.role === 'admin' || permissions.canMakeExpenseDeposits || permissions.canManageBusinessSettings
    if (!canCatchUp) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
    }

    const body = await request.json().catch(() => ({}))
    const allocationType: string = body?.allocationType
    const configKey: string = body?.configKey
    const requestedAmount: number | undefined = body?.amount != null ? Number(body.amount) : undefined

    if (!['RENT', 'AUTO_DEPOSIT', 'PAYROLL'].includes(allocationType) || !configKey) {
      return NextResponse.json({ error: 'allocationType and configKey are required' }, { status: 400 })
    }
    if (allocationType === 'PAYROLL' && configKey !== PAYROLL_ALLOCATION_CONFIG_KEY) {
      return NextResponse.json({ error: 'Invalid configKey for PAYROLL' }, { status: 400 })
    }

    const openSkips = await prisma.eodAllocationSkips.findMany({
      where: { businessId, allocationType, configKey, caughtUpAt: null },
      orderBy: { eodDate: 'asc' },
    })
    const rows = openSkips
      .map(s => ({ ...s, remaining: Number(s.amountSkipped) - Number(s.amountCaughtUp) }))
      .filter(s => s.remaining > 0.009)
    const totalOwed = rows.reduce((sum, s) => sum + s.remaining, 0)
    if (rows.length === 0 || totalOwed <= 0.009) {
      return NextResponse.json({ error: 'No outstanding backlog for this item' }, { status: 400 })
    }

    const todayStr = new Date().toISOString().slice(0, 10)
    const todayDateObj = new Date(todayStr + 'T12:00:00.000Z') // noon UTC — stable calendar date regardless of server timezone

    const result = await prisma.$transaction(async (tx) => {
      const availableCash = await getAvailableCashForAllocation(businessId, todayStr, undefined, tx)
      let amountToApply = Math.min(requestedAmount ?? totalOwed, totalOwed, availableCash)

      if (allocationType !== 'PAYROLL') {
        const expenseAccount = await tx.expenseAccounts.findUnique({
          where: { id: configKey },
          select: { id: true, accountName: true, balance: true, isLoanAccount: true, isActive: true },
        })
        if (!expenseAccount) throw new Error('Target account not found')
        // A loan may have been partly paid down by other means since these skips were
        // recorded — never catch up more than what's actually still owed on the loan.
        if (expenseAccount.isLoanAccount) {
          amountToApply = Math.min(amountToApply, Math.abs(Number(expenseAccount.balance)))
        }
        if (amountToApply <= 0.009) throw new Error('INSUFFICIENT_FUNDS:' + availableCash.toFixed(2))

        const bizAcct = await tx.businessAccounts.findUnique({ where: { businessId }, select: { balance: true } })
        const currentBalance = Number(bizAcct?.balance ?? 0)
        const sourceType = allocationType === 'RENT' ? 'EOD_RENT_TRANSFER_CATCHUP' : 'EOD_AUTO_DEPOSIT_CATCHUP'

        const deposit = await tx.expenseAccountDeposits.create({
          data: {
            expenseAccountId: expenseAccount.id,
            sourceType,
            sourceBusinessId: businessId,
            amount: amountToApply,
            depositDate: todayDateObj,
            autoGeneratedNote: `Manual catch-up toward ${rows.length} missed day(s) ($${totalOwed.toFixed(2)} owed) for ${expenseAccount.accountName}`,
            createdBy: user.id,
          },
        })

        await tx.expenseAccounts.update({
          where: { id: expenseAccount.id },
          data: { balance: { increment: amountToApply }, updatedAt: new Date() },
        })
        await tx.businessAccounts.update({ where: { businessId }, data: { balance: { decrement: amountToApply } } })
        await tx.businessTransactions.create({
          data: {
            businessId,
            type: 'DEBIT',
            amount: -amountToApply,
            description: `Manual catch-up transfer to ${expenseAccount.accountName}`,
            balanceAfter: currentBalance - amountToApply,
            createdBy: user.id,
            referenceType: allocationType === 'RENT' ? 'RENT_TRANSFER' : 'EXPENSE_DEPOSIT',
            referenceId: expenseAccount.id,
          },
        })
        await tx.cashBucketEntry.create({
          data: {
            businessId,
            entryType: 'CASH_ALLOCATION',
            direction: 'OUTFLOW',
            amount: amountToApply,
            referenceType: sourceType,
            referenceId: deposit.id,
            notes: expenseAccount.accountName, // groups with the account's normal entries, same as the regular EOD path
            entryDate: todayDateObj,
            createdBy: user.id,
          },
        })

        if (expenseAccount.isLoanAccount) {
          const newBalance = Number(expenseAccount.balance) + amountToApply
          if (newBalance >= 0) {
            await tx.businessLoan.updateMany({
              where: { expenseAccountId: expenseAccount.id, status: 'LOCKED' },
              data: { status: 'SETTLED', settledAt: new Date() },
            })
          }
        }
      } else {
        if (amountToApply <= 0.009) throw new Error('INSUFFICIENT_FUNDS:' + availableCash.toFixed(2))

        const payrollAccount = await tx.payrollAccounts.findFirst({ where: { businessId: null, isActive: true }, select: { id: true, balance: true } })
        if (!payrollAccount) throw new Error('Global payroll account not found')

        const bizAcct = await tx.businessAccounts.findUnique({ where: { businessId }, select: { balance: true } })
        const currentBalance = Number(bizAcct?.balance ?? 0)

        const deposit = await tx.payrollAccountDeposits.create({
          data: {
            payrollAccountId: payrollAccount.id,
            businessId,
            amount: amountToApply,
            depositDate: todayDateObj,
            transactionType: 'CATCHUP_CONTRIBUTION',
            autoGeneratedNote: `Manual catch-up toward ${rows.length} missed day(s) ($${totalOwed.toFixed(2)} owed) for payroll`,
            createdBy: user.id,
          },
        })
        await tx.payrollAccounts.update({ where: { id: payrollAccount.id }, data: { balance: { increment: amountToApply } } })
        await tx.businessAccounts.update({ where: { businessId }, data: { balance: { decrement: amountToApply } } })
        await tx.businessTransactions.create({
          data: {
            businessId,
            type: 'DEBIT',
            amount: -amountToApply,
            description: 'Manual catch-up payroll contribution',
            balanceAfter: currentBalance - amountToApply,
            createdBy: user.id,
            referenceType: 'PAYROLL_DEPOSIT',
            referenceId: payrollAccount.id,
          },
        })
        await tx.cashBucketEntry.create({
          data: {
            businessId,
            entryType: 'PAYROLL_FUNDING',
            direction: 'OUTFLOW',
            amount: amountToApply,
            referenceType: 'PAYROLL_ACCOUNT',
            referenceId: deposit.id,
            notes: 'EOD payroll auto-contribution', // same notes as the regular path so they group together
            entryDate: todayDateObj,
            createdBy: user.id,
          },
        })
      }

      // Apply the catch-up to the oldest outstanding skip rows first.
      let remainingToApply = amountToApply
      for (const row of rows) {
        if (remainingToApply <= 0.009) break
        const portion = Math.min(row.remaining, remainingToApply)
        const newCaughtUp = Number(row.amountCaughtUp) + portion
        const fullyResolved = newCaughtUp >= Number(row.amountSkipped) - 0.009
        await tx.eodAllocationSkips.update({
          where: { id: row.id },
          data: {
            amountCaughtUp: newCaughtUp,
            caughtUpAt: fullyResolved ? new Date() : null,
          },
        })
        remainingToApply -= portion
      }

      return { amountApplied: amountToApply }
    }).catch((err: any) => {
      if (err?.message?.startsWith('INSUFFICIENT_FUNDS:')) {
        return { error: `No cash available to catch up right now (available $${err.message.split(':')[1]})` }
      }
      throw err
    })

    if ('error' in result) {
      return NextResponse.json({ error: result.error }, { status: 422 })
    }

    const remainingOwed = Math.max(0, totalOwed - result.amountApplied)
    return NextResponse.json({
      success: true,
      amountApplied: result.amountApplied,
      remainingOwed,
      message: remainingOwed > 0.009
        ? `Caught up $${result.amountApplied.toFixed(2)} — $${remainingOwed.toFixed(2)} still owed (limited by available cash)`
        : `Fully caught up $${result.amountApplied.toFixed(2)}`,
    })
  } catch (err: any) {
    console.error('[POST /api/business/[businessId]/allocation-backlog/catch-up]', err)
    return NextResponse.json({ error: err?.message || 'Internal server error' }, { status: 500 })
  }
}
