-- Migration: add_node_state
-- Generated by assistant

CREATE TABLE IF NOT EXISTS "node_states" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "nodeId" TEXT NOT NULL UNIQUE,
  "nodeName" TEXT NOT NULL,
  "lastSeen" TIMESTAMP NOT NULL DEFAULT now(),
  "isOnline" BOOLEAN NOT NULL DEFAULT false,
  "syncVersion" TEXT NOT NULL,
  "metadata" JSONB,
  "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "node_states_nodeId_idx" ON "node_states" ("nodeId");
